# 
# Synthesis run script generated by Vivado
# 

set_msg_config  -ruleid {1}  -id {BD 41-968}  -string {{xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {2}  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_M_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {3}  -id {BD 41-967}  -string {{xillybus_ip_0/xillybus_S_AXI}}  -new_severity {INFO} 
set_msg_config  -ruleid {4}  -id {BD 41-678}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -ruleid {5}  -id {BD 41-1356}  -string {{xillybus_S_AXI/Reg}}  -new_severity {INFO} 
set_msg_config  -ruleid {7}  -id {BD 41-759}  -string {{xlconcat_0/In}}  -new_severity {INFO} 
set_msg_config  -ruleid {8}  -id {Netlist 29-160}  -string {{vivado_system_processing_system7}}  -new_severity {INFO} 
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/vivado/xillydemo.cache/wt [current_project]
set_property parent.project_path /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/vivado/xillydemo.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado-ip [current_project]
add_files -quiet /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vga_fifo/vga_fifo.dcp
set_property used_in_implementation false [get_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vga_fifo/vga_fifo.dcp]
add_files -quiet /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.dcp
set_property used_in_implementation false [get_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/fifo_8x2048/fifo_8x2048.dcp]
add_files -quiet /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512.dcp
set_property used_in_implementation false [get_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/fifo_32x512/fifo_32x512.dcp]
add_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/vivado_system.bd
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_processing_system7_0_0/vivado_system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_rst_processing_system7_0_100M_0/vivado_system_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_xbar_0/vivado_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_0/vivado_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_1/vivado_system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_2/vivado_system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/ip/vivado_system_auto_pc_3/vivado_system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/vivado_system_ooc.xdc]
set_property is_locked true [get_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/vivado_system/vivado_system.bd]

read_ip -quiet /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/vivado/xillydemo.srcs/sources_1/ip/dut_ap_sitofp_4_no_dsp_32/dut_ap_sitofp_4_no_dsp_32.xci
set_property is_locked true [get_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/vivado/xillydemo.srcs/sources_1/ip/dut_ap_sitofp_4_no_dsp_32/dut_ap_sitofp_4_no_dsp_32.xci]

read_verilog -library xil_defaultlib {
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/xillydemo.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/xillybus_core.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/xillybus.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/system.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/smbus.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/i2s_audio.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_urem_9ns_9ns_9_13.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_urem_13ns_9ns_13_17.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_urem_13ns_9ns_13_17_seq.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_sitofp_32ns_32_6.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_result.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_perform_conv_w_conv1_0.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_perform_conv.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_perform_conv_b_conv1.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_perform_conv_1_w_conv2.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_perform_conv_1.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_perform_conv_1_b_conv2.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_mux_4to1_sel32_32_1.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_mul_mul_15ns_13ns_28_1.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_mul_32s_30s_61_6.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_cnn_xcel.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_cnn_xcel_mem_conv2_V.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_cnn_xcel_mem_conv1_1_V.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fpga-design/dut_cnn_xcel_mem_conv1_0_V.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fifo_8x2048.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/xillybus/src/fifo_32x512.v
  /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/system.v
}
set_property edif_extra_search_paths /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/cores [current_fileset]
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/xillydemo.xdc
set_property used_in_implementation false [get_files /home/srs383/ECE5775/Labs/lab4/ecelinux/zedboard_project/vivado-essentials/xillydemo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top xillydemo -part xc7z020clg484-1


write_checkpoint -force -noxdef xillydemo.dcp

catch { report_utilization -file xillydemo_utilization_synth.rpt -pb xillydemo_utilization_synth.pb }
