// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __dut_perform_conv_b_conv1_1_H__
#define __dut_perform_conv_b_conv1_1_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct dut_perform_conv_b_conv1_1_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 28;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(dut_perform_conv_b_conv1_1_ram) {
        ram[0] = "0b0110111011101100000001100000";
        ram[1] = "0b0111110111100010111111100111";
        ram[2] = "0b0111100100100000010111101000";
        ram[3] = "0b1000010111000011111010011111";
        ram[4] = "0b0111011101111101101010100000";
        ram[5] = "0b1000111101011010010010011111";
        ram[6] = "0b0110111001101100011111100111";
        ram[7] = "0b0110010110010001000111101000";
        for (unsigned i = 8; i < 16 ; i = i + 1) {
            ram[i] = "0b0000000000000000000000000000";
        }


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(dut_perform_conv_b_conv1_1) {


static const unsigned DataWidth = 28;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


dut_perform_conv_b_conv1_1_ram* meminst;


SC_CTOR(dut_perform_conv_b_conv1_1) {
meminst = new dut_perform_conv_b_conv1_1_ram("dut_perform_conv_b_conv1_1_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~dut_perform_conv_b_conv1_1() {
    delete meminst;
}


};//endmodule
#endif
