// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_perform_conv (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_V_address0,
        input_0_V_ce0,
        input_0_V_q0,
        input_0_V_address1,
        input_0_V_ce1,
        input_0_V_q1,
        input_1_V_address0,
        input_1_V_ce0,
        input_1_V_q0,
        input_2_V_address0,
        input_2_V_ce0,
        input_2_V_q0,
        input_3_V_address0,
        input_3_V_ce0,
        input_3_V_q0,
        output_V_address0,
        output_V_ce0,
        output_V_we0,
        output_V_d0,
        output_V_q0
);

parameter    ap_ST_st1_fsm_0 = 13'b1;
parameter    ap_ST_st2_fsm_1 = 13'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 13'b100;
parameter    ap_ST_pp0_stg1_fsm_3 = 13'b1000;
parameter    ap_ST_pp0_stg2_fsm_4 = 13'b10000;
parameter    ap_ST_pp0_stg3_fsm_5 = 13'b100000;
parameter    ap_ST_pp0_stg4_fsm_6 = 13'b1000000;
parameter    ap_ST_st29_fsm_7 = 13'b10000000;
parameter    ap_ST_st30_fsm_8 = 13'b100000000;
parameter    ap_ST_st31_fsm_9 = 13'b1000000000;
parameter    ap_ST_st32_fsm_10 = 13'b10000000000;
parameter    ap_ST_st33_fsm_11 = 13'b100000000000;
parameter    ap_ST_st34_fsm_12 = 13'b1000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv10_320 = 10'b1100100000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv6_19 = 6'b11001;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv3_5 = 3'b101;
parameter    ap_const_lv9_3 = 9'b11;
parameter    ap_const_lv3_1 = 3'b1;
parameter    ap_const_lv9_C8 = 9'b11001000;
parameter    ap_const_lv6_7 = 6'b111;
parameter    ap_const_lv6_E = 6'b1110;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv9_6 = 9'b110;
parameter    ap_const_lv3_3 = 3'b11;
parameter    ap_const_lv9_4 = 9'b100;
parameter    ap_const_lv9_7 = 9'b111;
parameter    ap_const_lv9_5 = 9'b101;
parameter    ap_const_lv9_8 = 9'b1000;
parameter    ap_const_lv9_1 = 9'b1;
parameter    ap_const_lv20_290 = 20'b1010010000;
parameter    ap_const_lv32_11 = 32'b10001;
parameter    ap_const_lv32_13 = 32'b10011;
parameter    ap_const_lv9_2 = 9'b10;
parameter    ap_const_lv10_19 = 10'b11001;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_3C = 32'b111100;
parameter    ap_const_lv30_0 = 30'b000000000000000000000000000000;
parameter    ap_const_lv32_3D = 32'b111101;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv6_20 = 6'b100000;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] input_0_V_address0;
output   input_0_V_ce0;
input  [31:0] input_0_V_q0;
output  [7:0] input_0_V_address1;
output   input_0_V_ce1;
input  [31:0] input_0_V_q1;
output  [7:0] input_1_V_address0;
output   input_1_V_ce0;
input  [31:0] input_1_V_q0;
output  [7:0] input_2_V_address0;
output   input_2_V_ce0;
input  [31:0] input_2_V_q0;
output  [7:0] input_3_V_address0;
output   input_3_V_ce0;
input  [31:0] input_3_V_q0;
output  [9:0] output_V_address0;
output   output_V_ce0;
output   output_V_we0;
output  [31:0] output_V_d0;
input  [31:0] output_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] input_0_V_address0;
reg input_0_V_ce0;
reg[7:0] input_0_V_address1;
reg input_0_V_ce1;
reg[7:0] input_1_V_address0;
reg input_1_V_ce0;
reg[7:0] input_2_V_address0;
reg input_2_V_ce0;
reg[7:0] input_3_V_address0;
reg input_3_V_ce0;
reg[9:0] output_V_address0;
reg output_V_ce0;
reg output_V_we0;
reg[31:0] output_V_d0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_30;
reg   [12:0] w_conv1_0_address0;
reg    w_conv1_0_ce0;
wire  signed [29:0] w_conv1_0_q0;
reg   [12:0] w_conv1_0_address1;
reg    w_conv1_0_ce1;
wire  signed [29:0] w_conv1_0_q1;
wire   [5:0] b_conv1_address0;
reg    b_conv1_ce0;
wire   [27:0] b_conv1_q0;
reg   [9:0] indvar_flatten3_reg_430;
reg   [5:0] t_V_1_reg_441;
reg   [5:0] ap_reg_ppstg_t_V_1_reg_441_pp0_iter1;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_98;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg    ap_reg_ppiten_pp0_it3;
reg    ap_reg_ppiten_pp0_it4;
reg    ap_reg_ppiten_pp0_it5;
reg   [5:0] ap_reg_ppstg_t_V_1_reg_441_pp0_iter2;
reg   [5:0] ap_reg_ppstg_t_V_1_reg_441_pp0_iter3;
reg   [5:0] indvar_flatten4_reg_453;
reg   [0:0] t_V_3_reg_464;
reg   [5:0] indvar_flatten_reg_475;
reg   [2:0] t_V_7_reg_486;
reg   [2:0] t_V_5_reg_497;
reg   [2:0] ap_reg_ppstg_t_V_5_reg_497_pp0_iter1;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_3;
reg    ap_sig_130;
reg   [2:0] ap_reg_ppstg_t_V_5_reg_497_pp0_iter2;
reg   [2:0] ap_reg_ppstg_t_V_5_reg_497_pp0_iter3;
reg  signed [29:0] reg_554;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_4;
reg    ap_sig_140;
reg   [0:0] exitcond_flatten4_reg_1929;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_5;
reg    ap_sig_152;
reg   [0:0] ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2;
reg  signed [31:0] reg_559;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_6;
reg    ap_sig_166;
reg  signed [31:0] reg_564;
reg  signed [29:0] reg_569;
wire   [0:0] exitcond1_fu_573_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_188;
wire   [9:0] i_V_fu_579_p2;
wire   [0:0] exitcond_flatten4_fu_626_p2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3;
reg   [0:0] ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4;
wire   [9:0] indvar_flatten_next4_fu_632_p2;
reg   [9:0] indvar_flatten_next4_reg_1933;
wire   [0:0] exitcond_flatten_fu_638_p2;
reg   [0:0] exitcond_flatten_reg_1938;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter3;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter4;
wire   [5:0] n_V_fu_656_p2;
reg   [5:0] n_V_reg_1944;
reg   [5:0] ap_reg_ppstg_n_V_reg_1944_pp0_iter1;
reg   [5:0] ap_reg_ppstg_n_V_reg_1944_pp0_iter2;
reg   [5:0] ap_reg_ppstg_n_V_reg_1944_pp0_iter3;
reg   [5:0] ap_reg_ppstg_n_V_reg_1944_pp0_iter4;
wire   [0:0] exitcond_flatten_mid_fu_726_p2;
reg   [0:0] exitcond_flatten_mid_reg_1949;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter3;
reg   [0:0] ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter4;
wire   [5:0] t_V_1_mid2_fu_732_p3;
reg   [5:0] t_V_1_mid2_reg_1954;
wire   [0:0] tmp_24_fu_752_p2;
reg   [0:0] tmp_24_reg_1959;
wire   [8:0] OP2_V_cast_mid2_v_v_fu_806_p3;
reg   [8:0] OP2_V_cast_mid2_v_v_reg_1966;
reg   [8:0] ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter1;
reg   [8:0] ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter2;
wire   [0:0] exitcond7_mid2_fu_826_p2;
reg   [0:0] exitcond7_mid2_reg_1979;
reg   [0:0] ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter1;
reg   [0:0] ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter2;
reg   [0:0] ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter3;
reg   [0:0] ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter4;
wire   [0:0] t_V_3_mid2_fu_832_p3;
reg   [0:0] t_V_3_mid2_reg_1987;
wire   [2:0] t_V_7_mid2_fu_852_p3;
reg   [2:0] t_V_7_mid2_reg_1992;
reg   [2:0] ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter1;
reg   [2:0] ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter2;
reg   [2:0] ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter3;
reg   [2:0] ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter4;
wire   [2:0] tmp2_fu_860_p2;
reg   [2:0] tmp2_reg_1999;
wire   [5:0] indvar_flatten_next_fu_872_p3;
reg   [5:0] indvar_flatten_next_reg_2005;
wire   [5:0] indvar_flatten_next3_fu_886_p3;
reg   [5:0] indvar_flatten_next3_reg_2010;
wire   [2:0] t_V_5_mid_fu_894_p3;
reg   [2:0] t_V_5_mid_reg_2015;
wire   [2:0] x_V_2_dup_fu_911_p2;
reg   [2:0] x_V_2_dup_reg_2026;
reg   [2:0] ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter1;
reg   [2:0] ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter2;
reg   [2:0] ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter3;
reg   [2:0] ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter4;
wire   [2:0] t_V_5_cast3_mid2_fu_917_p3;
reg   [2:0] t_V_5_cast3_mid2_reg_2031;
wire  signed [8:0] tmp1_cast19_cast_fu_952_p1;
reg  signed [8:0] tmp1_cast19_cast_reg_2036;
wire   [8:0] i_index_V_fu_956_p2;
reg   [8:0] i_index_V_reg_2042;
reg   [8:0] ap_reg_ppstg_i_index_V_reg_2042_pp0_iter1;
reg   [8:0] ap_reg_ppstg_i_index_V_reg_2042_pp0_iter2;
wire   [5:0] tmp1_0_1_cast_fu_972_p2;
reg   [5:0] tmp1_0_1_cast_reg_2048;
wire   [5:0] tmp1_0_2_cast_fu_989_p2;
reg   [5:0] tmp1_0_2_cast_reg_2059;
wire   [8:0] i_index_V_1_fu_1082_p2;
reg   [8:0] i_index_V_1_reg_2075;
reg   [8:0] ap_reg_ppstg_i_index_V_1_reg_2075_pp0_iter1;
reg   [8:0] ap_reg_ppstg_i_index_V_1_reg_2075_pp0_iter2;
wire   [8:0] i_index_V_2_fu_1113_p2;
reg   [8:0] i_index_V_2_reg_2091;
reg   [8:0] ap_reg_ppstg_i_index_V_2_reg_2091_pp0_iter1;
reg   [8:0] ap_reg_ppstg_i_index_V_2_reg_2091_pp0_iter2;
wire   [5:0] i_index_V_2_1_fu_1118_p2;
reg   [5:0] i_index_V_2_1_reg_2097;
wire   [5:0] i_index_V_2_2_fu_1123_p2;
reg   [5:0] i_index_V_2_2_reg_2102;
wire   [2:0] y_V_1_fu_1227_p2;
reg   [2:0] y_V_1_reg_2172;
wire   [60:0] grp_fu_1160_p2;
reg   [60:0] p_Val2_7_0_1_reg_2202;
reg   [60:0] ap_reg_ppstg_p_Val2_7_0_1_reg_2202_pp0_iter2;
reg   [60:0] ap_reg_ppstg_p_Val2_7_0_1_reg_2202_pp0_iter3;
wire   [60:0] grp_fu_1170_p2;
reg   [60:0] p_Val2_7_0_2_reg_2207;
reg   [60:0] ap_reg_ppstg_p_Val2_7_0_2_reg_2207_pp0_iter2;
reg   [60:0] ap_reg_ppstg_p_Val2_7_0_2_reg_2207_pp0_iter3;
wire   [60:0] grp_fu_1207_p2;
reg   [60:0] p_Val2_7_1_1_reg_2212;
reg   [60:0] ap_reg_ppstg_p_Val2_7_1_1_reg_2212_pp0_iter2;
reg   [60:0] ap_reg_ppstg_p_Val2_7_1_1_reg_2212_pp0_iter3;
wire   [60:0] grp_fu_1217_p2;
reg   [60:0] p_Val2_7_1_2_reg_2217;
reg   [60:0] ap_reg_ppstg_p_Val2_7_1_2_reg_2217_pp0_iter2;
reg   [60:0] ap_reg_ppstg_p_Val2_7_1_2_reg_2217_pp0_iter3;
wire   [60:0] grp_fu_1250_p2;
reg   [60:0] p_Val2_7_2_1_reg_2222;
reg   [60:0] ap_reg_ppstg_p_Val2_7_2_1_reg_2222_pp0_iter3;
reg   [60:0] ap_reg_ppstg_p_Val2_7_2_1_reg_2222_pp0_iter4;
wire   [60:0] grp_fu_1264_p2;
reg   [60:0] p_Val2_7_2_2_reg_2232;
reg   [60:0] ap_reg_ppstg_p_Val2_7_2_2_reg_2232_pp0_iter3;
reg   [60:0] ap_reg_ppstg_p_Val2_7_2_2_reg_2232_pp0_iter4;
reg   [2:0] tmp_34_reg_2242;
reg   [2:0] tmp_38_reg_2267;
wire   [31:0] tmp_s_fu_1347_p6;
reg  signed [31:0] tmp_s_reg_2277;
reg   [2:0] tmp_39_reg_2302;
wire   [31:0] tmp_10_fu_1408_p6;
reg  signed [31:0] tmp_10_reg_2317;
wire   [31:0] tmp_11_fu_1450_p6;
reg  signed [31:0] tmp_11_reg_2352;
wire   [9:0] p_1_fu_1481_p2;
reg   [9:0] p_1_reg_2367;
wire   [9:0] tmp4_fu_1491_p2;
reg   [9:0] tmp4_reg_2372;
reg   [30:0] tmp_36_reg_2377;
wire   [9:0] p_1_mid1_fu_1510_p2;
reg   [9:0] p_1_mid1_reg_2382;
wire   [60:0] grp_fu_1437_p2;
reg   [60:0] p_Val2_7_1_reg_2388;
reg   [31:0] tmp_27_reg_2393;
reg   [31:0] tmp_30_reg_2398;
wire   [60:0] grp_fu_1471_p2;
reg   [60:0] p_Val2_7_2_reg_2403;
wire   [9:0] o_index_V_fu_1679_p2;
reg   [9:0] o_index_V_reg_2408;
reg   [31:0] tmp_41_reg_2413;
reg   [31:0] sum_V_2_2_reg_2418;
reg   [9:0] output_V_addr_2_reg_2423;
wire   [9:0] next_mul_fu_1801_p2;
reg   [9:0] next_mul_reg_2428;
reg    ap_sig_cseq_ST_st29_fsm_7;
reg    ap_sig_488;
wire   [5:0] n_V_1_fu_1813_p2;
reg   [5:0] n_V_1_reg_2436;
wire   [0:0] exitcond3_fu_1807_p2;
wire   [31:0] p_Val2_3_cast_fu_1824_p1;
reg   [31:0] p_Val2_3_cast_reg_2446;
reg    ap_sig_cseq_ST_st30_fsm_8;
reg    ap_sig_504;
wire   [2:0] x_V_fu_1838_p2;
reg   [2:0] x_V_reg_2454;
reg    ap_sig_cseq_ST_st31_fsm_9;
reg    ap_sig_513;
wire   [9:0] tmp6_fu_1844_p2;
reg   [9:0] tmp6_reg_2459;
wire   [0:0] exitcond5_fu_1832_p2;
wire   [2:0] y_V_fu_1860_p2;
reg   [2:0] y_V_reg_2467;
reg    ap_sig_cseq_ST_st32_fsm_10;
reg    ap_sig_527;
reg   [9:0] output_V_addr_1_reg_2472;
wire   [0:0] exitcond_fu_1854_p2;
wire   [30:0] tmp_43_fu_1899_p1;
reg   [30:0] tmp_43_reg_2477;
reg    ap_sig_cseq_ST_st33_fsm_11;
reg    ap_sig_541;
wire   [0:0] tmp_8_fu_1903_p2;
reg   [0:0] tmp_8_reg_2482;
reg   [9:0] t_V_reg_419;
reg   [9:0] indvar_flatten3_phi_fu_434_p4;
reg   [5:0] t_V_1_phi_fu_445_p4;
reg   [5:0] indvar_flatten4_phi_fu_457_p4;
reg   [0:0] t_V_3_phi_fu_468_p4;
reg   [5:0] indvar_flatten_phi_fu_479_p4;
reg   [2:0] t_V_7_phi_fu_490_p4;
reg   [2:0] t_V_5_phi_fu_501_p4;
reg   [5:0] t_V_2_reg_509;
reg   [9:0] phi_mul_reg_520;
reg   [2:0] t_V_4_reg_532;
reg   [2:0] t_V_6_reg_543;
reg    ap_sig_cseq_ST_st34_fsm_12;
reg    ap_sig_592;
wire   [63:0] tmp_2_fu_585_p1;
wire   [63:0] OP2_V_0_1_mid2_v_fu_906_p1;
wire   [63:0] newIndex_fu_984_p1;
wire   [63:0] newIndex1_fu_1001_p1;
wire   [63:0] OP2_V_0_2_mid2_v_fu_1023_p1;
wire   [63:0] newIndex4_fu_1098_p1;
wire   [63:0] newIndex5_fu_1108_p1;
wire   [63:0] OP2_V_1_1_mid2_v_fu_1141_p1;
wire   [63:0] OP2_V_1_2_mid2_v_fu_1151_p1;
wire   [63:0] newIndex11_fu_1181_p1;
wire   [63:0] OP2_V_2_1_mid2_v_fu_1198_p1;
wire   [63:0] newIndex7_fu_1223_p1;
wire   [63:0] OP2_V_2_2_mid2_v_fu_1241_p1;
wire   [63:0] OP2_V_cast_mid2_v_fu_1270_p1;
wire   [63:0] OP2_V_1_mid2_v_fu_1279_p1;
wire   [63:0] newIndex8_fu_1303_p1;
wire   [63:0] OP2_V_2_mid2_v_fu_1335_p1;
wire   [63:0] newIndex3_fu_1361_p1;
wire   [63:0] newIndex10_fu_1422_p1;
wire   [63:0] tmp_3_fu_1791_p1;
wire   [63:0] tmp_4_fu_1819_p1;
wire   [63:0] tmp_1_fu_1889_p1;
wire   [31:0] p_Val2_5_fu_1795_p2;
wire   [31:0] p_Val2_2_cast_fu_1915_p1;
wire   [5:0] t_V_3_cast_fu_590_p1;
wire   [5:0] tmp_6_fu_594_p2;
wire   [4:0] tmp_29_fu_604_p1;
wire   [7:0] p_shl_fu_608_p3;
wire   [8:0] tmp_6_cast2_fu_600_p1;
wire   [8:0] p_shl_cast_fu_616_p1;
wire   [0:0] not_exitcond_flatten_fu_644_p2;
wire   [0:0] not_exitcond_flatten1_fu_662_p2;
wire   [4:0] tmp_31_fu_678_p1;
wire   [7:0] p_shl_mid_fu_682_p3;
wire   [8:0] tmp_6_cast2_mid_fu_674_p1;
wire   [8:0] p_shl_cast_mid_fu_690_p1;
wire   [8:0] tmp_7_mid_fu_694_p2;
wire   [8:0] tmp_7_fu_620_p2;
wire   [0:0] exitcond4_fu_708_p2;
wire   [0:0] exitcond_flatten2_fu_720_p2;
wire   [0:0] t_V_3_not_fu_740_p2;
wire   [0:0] m_V_fu_746_p2;
wire   [0:0] p_3_cast_mid_fu_668_p2;
wire   [0:0] p_3_cast_mid2_fu_762_p3;
wire   [5:0] t_V_3_cast_mid1_fu_758_p1;
wire   [5:0] tmp_6_mid1_fu_774_p2;
wire   [4:0] tmp_32_fu_784_p1;
wire   [7:0] p_shl_mid1_fu_788_p3;
wire   [8:0] tmp_6_cast2_mid1_fu_780_p1;
wire   [8:0] p_shl_cast_mid1_fu_796_p1;
wire   [8:0] tmp_7_mid1_fu_800_p2;
wire   [8:0] OP2_V_cast_mid2159_v_v_fu_700_p3;
wire   [0:0] exitcond_flatten_not_fu_814_p2;
wire   [0:0] exitcond7_mid_fu_714_p2;
wire   [0:0] not_exitcond_flatten_mid_fu_820_p2;
wire   [0:0] t_V_3_mid_fu_650_p2;
wire   [0:0] tmp_25_fu_840_p2;
wire   [0:0] tmp_33_fu_846_p2;
wire   [2:0] p_3_cast_mid2_cast_fu_770_p1;
wire   [5:0] indvar_flatten_op_fu_866_p2;
wire   [5:0] indvar_flatten40_op_fu_880_p2;
wire   [8:0] OP2_V_0_1_mid2_v_v_fu_901_p2;
wire   [5:0] p_shl3_fu_935_p3;
wire   [6:0] p_shl3_cast_fu_942_p1;
wire   [6:0] tmp2_cast1_fu_932_p1;
wire   [6:0] tmp1_fu_946_p2;
wire   [8:0] t_V_5_cast24_cast_mid2_cast_fu_928_p1;
wire   [8:0] grp_fu_962_p0;
wire   [5:0] tmp_35_fu_968_p1;
wire   [5:0] t_V_5_cast3_mid2_cast_fu_924_p1;
wire   [5:0] i_index_V_0_1_fu_978_p2;
wire   [5:0] i_index_V_0_2_fu_995_p2;
wire   [8:0] OP2_V_0_2_mid2_v_v_fu_1018_p2;
wire   [2:0] x_V_2_fu_1006_p2;
wire   [2:0] tmp_15_2_fu_1012_p2;
wire   [2:0] x_V_2_mid1_fu_1042_p2;
wire   [2:0] tmp_15_1_cast_mid_fu_1028_p3;
wire   [2:0] tmp_15_1_cast_mid2_fu_1047_p3;
wire   [2:0] tmp_15_2_mid1_fu_1062_p2;
wire   [2:0] tmp_15_2_cast_mid_fu_1035_p3;
wire   [2:0] tmp_15_2_cast_mid2_fu_1067_p3;
wire   [8:0] tmp_15_1_cast_cast_mid2_cast_fu_1058_p1;
wire   [8:0] grp_fu_1087_p0;
wire   [5:0] tmp_15_1_cast_mid2_cast_fu_1054_p1;
wire   [5:0] i_index_V_1_1_fu_1093_p2;
wire   [5:0] i_index_V_1_2_fu_1103_p2;
wire   [8:0] tmp_15_2_cast_cast_mid2_cast_fu_1078_p1;
wire   [5:0] tmp_15_2_cast_mid2_cast_fu_1074_p1;
wire   [8:0] OP2_V_1_1_mid2_v_v_fu_1136_p2;
wire   [8:0] OP2_V_1_2_mid2_v_v_fu_1146_p2;
wire   [8:0] OP2_V_2_1_mid2_v_v_fu_1193_p2;
wire   [8:0] OP2_V_2_2_mid2_v_v_fu_1236_p2;
wire   [8:0] OP2_V_1_mid2_v_v_fu_1274_p2;
wire   [8:0] mul3_fu_1287_p1;
wire   [19:0] mul3_fu_1287_p2;
wire   [8:0] grp_fu_962_p2;
wire   [8:0] mul4_fu_1314_p1;
wire   [19:0] mul4_fu_1314_p2;
wire   [8:0] OP2_V_2_mid2_v_v_fu_1330_p2;
wire  signed [8:0] arrayNo2_fu_1340_p1;
wire   [31:0] tmp_s_fu_1347_p5;
wire   [8:0] grp_fu_1087_p2;
wire   [8:0] mul_fu_1372_p1;
wire   [19:0] mul_fu_1372_p2;
wire  signed [8:0] arrayNo8_fu_1401_p1;
wire   [31:0] tmp_10_fu_1408_p5;
wire   [8:0] grp_fu_1176_p2;
wire  signed [8:0] arrayNo_fu_1443_p1;
wire   [31:0] tmp_11_fu_1450_p5;
wire   [5:0] p_1_fu_1481_p1;
wire   [9:0] t_V_5_cast_fu_1487_p1;
wire   [60:0] grp_fu_1395_p2;
wire   [5:0] p_1_mid1_fu_1510_p1;
wire   [60:0] tmp_37_fu_1519_p3;
wire  signed [61:0] p_Val2_7_0_1_cast_fu_1516_p1;
wire  signed [61:0] tmp_20_0_1_fu_1526_p1;
wire   [61:0] p_Val2_8_0_1_fu_1530_p2;
wire   [31:0] tmp_26_fu_1539_p4;
wire  signed [61:0] p_Val2_7_0_2_cast_fu_1536_p1;
wire   [61:0] tmp_20_0_2_fu_1549_p3;
wire   [61:0] p_Val2_8_0_2_fu_1557_p2;
wire   [9:0] p_1_mid2_fu_1573_p3;
wire   [9:0] tmp4_mid_fu_1578_p3;
wire   [9:0] t_V_5_cast_mid1_fu_1590_p1;
wire   [9:0] tmp4_mid1_fu_1593_p2;
wire   [9:0] tmp4_mid3_fu_1583_p3;
wire  signed [61:0] p_Val2_7_1_cast_fu_1609_p1;
wire   [61:0] tmp_20_1_fu_1612_p3;
wire   [61:0] p_Val2_8_1_fu_1619_p2;
wire   [31:0] tmp_28_fu_1628_p4;
wire  signed [61:0] p_Val2_7_1_1_cast_fu_1625_p1;
wire   [61:0] tmp_20_1_1_fu_1638_p3;
wire   [61:0] p_Val2_8_1_1_fu_1646_p2;
wire   [4:0] t_V_7_cast_fu_1606_p1;
wire   [4:0] p_shl2_fu_1662_p3;
wire   [4:0] tmp3_fu_1669_p2;
wire   [9:0] tmp3_cast_fu_1675_p1;
wire   [9:0] tmp4_mid2_fu_1599_p3;
wire  signed [61:0] p_Val2_7_1_2_cast_fu_1685_p1;
wire   [61:0] tmp_20_1_2_fu_1688_p3;
wire   [61:0] p_Val2_8_1_2_fu_1695_p2;
wire   [31:0] tmp_40_fu_1704_p4;
wire  signed [61:0] p_Val2_7_2_cast_fu_1701_p1;
wire   [61:0] tmp_20_2_fu_1714_p3;
wire   [61:0] p_Val2_8_2_fu_1722_p2;
wire  signed [61:0] p_Val2_7_2_1_cast_fu_1738_p1;
wire   [61:0] tmp_20_2_1_fu_1741_p3;
wire   [61:0] p_Val2_8_2_1_fu_1748_p2;
wire   [31:0] tmp_42_fu_1757_p4;
wire  signed [61:0] p_Val2_7_2_2_cast_fu_1754_p1;
wire   [61:0] tmp_20_2_2_fu_1767_p3;
wire   [61:0] p_Val2_8_2_2_fu_1775_p2;
wire   [9:0] t_V_4_cast8_fu_1828_p1;
wire   [4:0] p_shl4_fu_1866_p3;
wire   [4:0] t_V_6_cast7_fu_1850_p1;
wire   [4:0] tmp5_fu_1874_p2;
wire   [9:0] tmp5_cast_fu_1880_p1;
wire   [9:0] index_V_fu_1884_p2;
wire   [31:0] biased_V_fu_1894_p2;
wire   [30:0] p_Val2_2_s_fu_1909_p3;
reg   [12:0] ap_NS_fsm;
wire   [19:0] mul3_fu_1287_p10;
wire   [19:0] mul4_fu_1314_p10;
wire   [19:0] mul_fu_1372_p10;
wire   [9:0] p_1_fu_1481_p10;
wire   [9:0] p_1_mid1_fu_1510_p10;
reg    ap_sig_1575;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'b1;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
#0 ap_reg_ppiten_pp0_it3 = 1'b0;
#0 ap_reg_ppiten_pp0_it4 = 1'b0;
#0 ap_reg_ppiten_pp0_it5 = 1'b0;
end

dut_perform_conv_w_conv1_0 #(
    .DataWidth( 30 ),
    .AddressRange( 4608 ),
    .AddressWidth( 13 ))
w_conv1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_conv1_0_address0),
    .ce0(w_conv1_0_ce0),
    .q0(w_conv1_0_q0),
    .address1(w_conv1_0_address1),
    .ce1(w_conv1_0_ce1),
    .q1(w_conv1_0_q1)
);

dut_perform_conv_b_conv1 #(
    .DataWidth( 28 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
b_conv1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_conv1_address0),
    .ce0(b_conv1_ce0),
    .q0(b_conv1_q0)
);

dut_urem_9ns_9ns_9_13 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 9 ))
dut_urem_9ns_9ns_9_13_U1(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_962_p0),
    .din1(ap_const_lv9_C8),
    .ce(1'b1),
    .dout(grp_fu_962_p2)
);

dut_urem_9ns_9ns_9_13 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 9 ))
dut_urem_9ns_9ns_9_13_U2(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_1087_p0),
    .din1(ap_const_lv9_C8),
    .ce(1'b1),
    .dout(grp_fu_1087_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U3(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_559),
    .din1(reg_554),
    .ce(1'b1),
    .dout(grp_fu_1160_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_564),
    .din1(w_conv1_0_q0),
    .ce(1'b1),
    .dout(grp_fu_1170_p2)
);

dut_urem_9ns_9ns_9_13 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 9 ))
dut_urem_9ns_9ns_9_13_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(i_index_V_2_reg_2091),
    .din1(ap_const_lv9_C8),
    .ce(1'b1),
    .dout(grp_fu_1176_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_559),
    .din1(w_conv1_0_q0),
    .ce(1'b1),
    .dout(grp_fu_1207_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_564),
    .din1(w_conv1_0_q1),
    .ce(1'b1),
    .dout(grp_fu_1217_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_559),
    .din1(w_conv1_0_q0),
    .ce(1'b1),
    .dout(grp_fu_1250_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_559),
    .din1(w_conv1_0_q0),
    .ce(1'b1),
    .dout(grp_fu_1264_p2)
);

dut_mux_4to1_sel32_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_mux_4to1_sel32_32_1_U10(
    .din1(input_0_V_q0),
    .din2(input_1_V_q0),
    .din3(input_2_V_q0),
    .din4(input_3_V_q0),
    .din5(tmp_s_fu_1347_p5),
    .dout(tmp_s_fu_1347_p6)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_s_reg_2277),
    .din1(reg_569),
    .ce(1'b1),
    .dout(grp_fu_1395_p2)
);

dut_mux_4to1_sel32_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_mux_4to1_sel32_32_1_U12(
    .din1(input_0_V_q0),
    .din2(input_1_V_q0),
    .din3(input_2_V_q0),
    .din4(input_3_V_q0),
    .din5(tmp_10_fu_1408_p5),
    .dout(tmp_10_fu_1408_p6)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U13(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_10_reg_2317),
    .din1(reg_554),
    .ce(1'b1),
    .dout(grp_fu_1437_p2)
);

dut_mux_4to1_sel32_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_mux_4to1_sel32_32_1_U14(
    .din1(input_0_V_q0),
    .din2(input_1_V_q0),
    .din3(input_2_V_q0),
    .din4(input_3_V_q0),
    .din5(tmp_11_fu_1450_p5),
    .dout(tmp_11_fu_1450_p6)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U15(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_11_reg_2352),
    .din1(reg_569),
    .ce(1'b1),
    .dout(grp_fu_1471_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & ~(exitcond_flatten4_reg_1929 == 1'b0))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            ap_reg_ppiten_pp0_it1 <= ap_reg_ppiten_pp0_it0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
            ap_reg_ppiten_pp0_it4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_reg_ppiten_pp0_it3) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end else if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & ~(1'b1 == ap_reg_ppiten_pp0_it3)))) begin
            ap_reg_ppiten_pp0_it5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        indvar_flatten3_reg_430 <= ap_const_lv10_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        indvar_flatten3_reg_430 <= indvar_flatten_next4_reg_1933;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        indvar_flatten4_reg_453 <= ap_const_lv6_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        indvar_flatten4_reg_453 <= indvar_flatten_next3_reg_2010;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        indvar_flatten_reg_475 <= ap_const_lv6_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        indvar_flatten_reg_475 <= indvar_flatten_next_reg_2005;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it4) & ~(1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3))) begin
        phi_mul_reg_520 <= ap_const_lv10_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st31_fsm_9) & ~(1'b0 == exitcond5_fu_1832_p2))) begin
        phi_mul_reg_520 <= next_mul_reg_2428;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2))) begin
        reg_554 <= w_conv1_0_q1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        reg_554 <= w_conv1_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten4_reg_1929 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten4_reg_1929 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0)))) begin
        reg_559 <= input_0_V_q1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        reg_559 <= input_0_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if (ap_sig_1575) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            reg_564 <= input_0_V_q0;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            reg_564 <= input_0_V_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        t_V_1_reg_441 <= ap_const_lv6_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_1_reg_441 <= t_V_1_mid2_reg_1954;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it4) & ~(1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3))) begin
        t_V_2_reg_509 <= ap_const_lv6_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st31_fsm_9) & ~(1'b0 == exitcond5_fu_1832_p2))) begin
        t_V_2_reg_509 <= n_V_1_reg_2436;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        t_V_3_reg_464 <= 1'b0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_3_reg_464 <= t_V_3_mid2_reg_1987;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st32_fsm_10) & ~(1'b0 == exitcond_fu_1854_p2))) begin
        t_V_4_reg_532 <= x_V_reg_2454;
    end else if ((1'b1 == ap_sig_cseq_ST_st30_fsm_8)) begin
        t_V_4_reg_532 <= ap_const_lv3_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        t_V_5_reg_497 <= ap_const_lv3_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1))) begin
        t_V_5_reg_497 <= t_V_5_cast3_mid2_reg_2031;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st31_fsm_9) & (1'b0 == exitcond5_fu_1832_p2))) begin
        t_V_6_reg_543 <= ap_const_lv3_0;
    end else if ((1'b1 == ap_sig_cseq_ST_st34_fsm_12)) begin
        t_V_6_reg_543 <= y_V_reg_2467;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_573_p2))) begin
        t_V_7_reg_486 <= ap_const_lv3_0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_7_reg_486 <= y_V_1_reg_2172;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_573_p2))) begin
        t_V_reg_419 <= i_V_fu_579_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        t_V_reg_419 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == exitcond_flatten4_fu_626_p2))) begin
        OP2_V_cast_mid2_v_v_reg_1966 <= OP2_V_cast_mid2_v_v_fu_806_p3;
        exitcond7_mid2_reg_1979 <= exitcond7_mid2_fu_826_p2;
        exitcond_flatten_mid_reg_1949 <= exitcond_flatten_mid_fu_726_p2;
        exitcond_flatten_reg_1938 <= exitcond_flatten_fu_638_p2;
        n_V_reg_1944 <= n_V_fu_656_p2;
        t_V_7_mid2_reg_1992 <= t_V_7_mid2_fu_852_p3;
        tmp2_reg_1999 <= tmp2_fu_860_p2;
        tmp_24_reg_1959 <= tmp_24_fu_752_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)) begin
        ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter1 <= OP2_V_cast_mid2_v_v_reg_1966;
        ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter2 <= ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter1;
        ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter1 <= exitcond7_mid2_reg_1979;
        ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter2 <= ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter1;
        ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter3 <= ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter2;
        ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter4 <= ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter3;
        ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1 <= exitcond_flatten4_reg_1929;
        ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2 <= ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1;
        ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3 <= ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2;
        ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4 <= ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3;
        ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter1 <= exitcond_flatten_mid_reg_1949;
        ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter2 <= ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter1;
        ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter3 <= ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter2;
        ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter4 <= ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter3;
        ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter1 <= exitcond_flatten_reg_1938;
        ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter2 <= ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter1;
        ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter3 <= ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter2;
        ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter4 <= ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter3;
        ap_reg_ppstg_n_V_reg_1944_pp0_iter1 <= n_V_reg_1944;
        ap_reg_ppstg_n_V_reg_1944_pp0_iter2 <= ap_reg_ppstg_n_V_reg_1944_pp0_iter1;
        ap_reg_ppstg_n_V_reg_1944_pp0_iter3 <= ap_reg_ppstg_n_V_reg_1944_pp0_iter2;
        ap_reg_ppstg_n_V_reg_1944_pp0_iter4 <= ap_reg_ppstg_n_V_reg_1944_pp0_iter3;
        ap_reg_ppstg_p_Val2_7_2_1_reg_2222_pp0_iter3 <= p_Val2_7_2_1_reg_2222;
        ap_reg_ppstg_p_Val2_7_2_1_reg_2222_pp0_iter4 <= ap_reg_ppstg_p_Val2_7_2_1_reg_2222_pp0_iter3;
        ap_reg_ppstg_t_V_1_reg_441_pp0_iter1 <= t_V_1_reg_441;
        ap_reg_ppstg_t_V_1_reg_441_pp0_iter2 <= ap_reg_ppstg_t_V_1_reg_441_pp0_iter1;
        ap_reg_ppstg_t_V_1_reg_441_pp0_iter3 <= ap_reg_ppstg_t_V_1_reg_441_pp0_iter2;
        ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter1 <= t_V_7_mid2_reg_1992;
        ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter2 <= ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter1;
        ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter3 <= ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter2;
        ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter4 <= ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter3;
        exitcond_flatten4_reg_1929 <= exitcond_flatten4_fu_626_p2;
        p_1_reg_2367 <= p_1_fu_1481_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
        ap_reg_ppstg_i_index_V_1_reg_2075_pp0_iter1 <= i_index_V_1_reg_2075;
        ap_reg_ppstg_i_index_V_1_reg_2075_pp0_iter2 <= ap_reg_ppstg_i_index_V_1_reg_2075_pp0_iter1;
        ap_reg_ppstg_i_index_V_2_reg_2091_pp0_iter1 <= i_index_V_2_reg_2091;
        ap_reg_ppstg_i_index_V_2_reg_2091_pp0_iter2 <= ap_reg_ppstg_i_index_V_2_reg_2091_pp0_iter1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
        ap_reg_ppstg_i_index_V_reg_2042_pp0_iter1 <= i_index_V_reg_2042;
        ap_reg_ppstg_i_index_V_reg_2042_pp0_iter2 <= ap_reg_ppstg_i_index_V_reg_2042_pp0_iter1;
        ap_reg_ppstg_p_Val2_7_2_2_reg_2232_pp0_iter3 <= p_Val2_7_2_2_reg_2232;
        ap_reg_ppstg_p_Val2_7_2_2_reg_2232_pp0_iter4 <= ap_reg_ppstg_p_Val2_7_2_2_reg_2232_pp0_iter3;
        ap_reg_ppstg_t_V_5_reg_497_pp0_iter1 <= t_V_5_reg_497;
        ap_reg_ppstg_t_V_5_reg_497_pp0_iter2 <= ap_reg_ppstg_t_V_5_reg_497_pp0_iter1;
        ap_reg_ppstg_t_V_5_reg_497_pp0_iter3 <= ap_reg_ppstg_t_V_5_reg_497_pp0_iter2;
        ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter1 <= x_V_2_dup_reg_2026;
        ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter2 <= ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter1;
        ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter3 <= ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter2;
        ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter4 <= ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
        ap_reg_ppstg_p_Val2_7_0_1_reg_2202_pp0_iter2 <= p_Val2_7_0_1_reg_2202;
        ap_reg_ppstg_p_Val2_7_0_1_reg_2202_pp0_iter3 <= ap_reg_ppstg_p_Val2_7_0_1_reg_2202_pp0_iter2;
        ap_reg_ppstg_p_Val2_7_0_2_reg_2207_pp0_iter2 <= p_Val2_7_0_2_reg_2207;
        ap_reg_ppstg_p_Val2_7_0_2_reg_2207_pp0_iter3 <= ap_reg_ppstg_p_Val2_7_0_2_reg_2207_pp0_iter2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
        ap_reg_ppstg_p_Val2_7_1_1_reg_2212_pp0_iter2 <= p_Val2_7_1_1_reg_2212;
        ap_reg_ppstg_p_Val2_7_1_1_reg_2212_pp0_iter3 <= ap_reg_ppstg_p_Val2_7_1_1_reg_2212_pp0_iter2;
        ap_reg_ppstg_p_Val2_7_1_2_reg_2217_pp0_iter2 <= p_Val2_7_1_2_reg_2217;
        ap_reg_ppstg_p_Val2_7_1_2_reg_2217_pp0_iter3 <= ap_reg_ppstg_p_Val2_7_1_2_reg_2217_pp0_iter2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        i_index_V_1_reg_2075 <= i_index_V_1_fu_1082_p2;
        i_index_V_2_1_reg_2097 <= i_index_V_2_1_fu_1118_p2;
        i_index_V_2_2_reg_2102 <= i_index_V_2_2_fu_1123_p2;
        i_index_V_2_reg_2091 <= i_index_V_2_fu_1113_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        i_index_V_reg_2042 <= i_index_V_fu_956_p2;
        t_V_5_mid_reg_2015 <= t_V_5_mid_fu_894_p3;
        tmp1_0_1_cast_reg_2048 <= tmp1_0_1_cast_fu_972_p2;
        tmp1_0_2_cast_reg_2059 <= tmp1_0_2_cast_fu_989_p2;
        tmp1_cast19_cast_reg_2036 <= tmp1_cast19_cast_fu_952_p1;
        x_V_2_dup_reg_2026 <= x_V_2_dup_fu_911_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it0) & (1'b0 == exitcond_flatten4_fu_626_p2))) begin
        indvar_flatten_next3_reg_2010 <= indvar_flatten_next3_fu_886_p3;
        indvar_flatten_next_reg_2005 <= indvar_flatten_next_fu_872_p3;
        t_V_1_mid2_reg_1954 <= t_V_1_mid2_fu_732_p3;
        t_V_3_mid2_reg_1987 <= t_V_3_mid2_fu_832_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        indvar_flatten_next4_reg_1933 <= indvar_flatten_next4_fu_632_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st29_fsm_7)) begin
        n_V_1_reg_2436 <= n_V_1_fu_1813_p2;
        next_mul_reg_2428 <= next_mul_fu_1801_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4))) begin
        o_index_V_reg_2408 <= o_index_V_fu_1679_p2;
        p_Val2_7_2_reg_2403 <= grp_fu_1471_p2;
        tmp_30_reg_2398 <= {{p_Val2_8_1_1_fu_1646_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st32_fsm_10) & (1'b0 == exitcond_fu_1854_p2))) begin
        output_V_addr_1_reg_2472 <= tmp_1_fu_1889_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4))) begin
        output_V_addr_2_reg_2423 <= tmp_3_fu_1791_p1;
        sum_V_2_2_reg_2418 <= {{p_Val2_8_2_2_fu_1775_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4))) begin
        p_1_mid1_reg_2382 <= p_1_mid1_fu_1510_p2;
        p_Val2_7_1_reg_2388 <= grp_fu_1437_p2;
        tmp_27_reg_2393 <= {{p_Val2_8_0_2_fu_1557_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st30_fsm_8)) begin
        p_Val2_3_cast_reg_2446[27 : 0] <= p_Val2_3_cast_fu_1824_p1[27 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1))) begin
        p_Val2_7_0_1_reg_2202 <= grp_fu_1160_p2;
        p_Val2_7_0_2_reg_2207 <= grp_fu_1170_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1))) begin
        p_Val2_7_1_1_reg_2212 <= grp_fu_1207_p2;
        p_Val2_7_1_2_reg_2217 <= grp_fu_1217_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1))) begin
        p_Val2_7_2_1_reg_2222 <= grp_fu_1250_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2))) begin
        p_Val2_7_2_2_reg_2232 <= grp_fu_1264_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2)))) begin
        reg_569 <= w_conv1_0_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_5_cast3_mid2_reg_2031 <= t_V_5_cast3_mid2_fu_917_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter3) & (1'b0 == ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter3) & (1'b0 == ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter3))) begin
        tmp4_reg_2372 <= tmp4_fu_1491_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st31_fsm_9) & (1'b0 == exitcond5_fu_1832_p2))) begin
        tmp6_reg_2459 <= tmp6_fu_1844_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2))) begin
        tmp_10_reg_2317 <= tmp_10_fu_1408_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3))) begin
        tmp_11_reg_2352 <= tmp_11_fu_1450_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2))) begin
        tmp_34_reg_2242 <= {{mul3_fu_1287_p2[ap_const_lv32_13 : ap_const_lv32_11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter3))) begin
        tmp_36_reg_2377 <= {{grp_fu_1395_p2[ap_const_lv32_3C : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2))) begin
        tmp_38_reg_2267 <= {{mul4_fu_1314_p2[ap_const_lv32_13 : ap_const_lv32_11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        tmp_39_reg_2302 <= {{mul_fu_1372_p2[ap_const_lv32_13 : ap_const_lv32_11]}};
        tmp_s_reg_2277 <= tmp_s_fu_1347_p6;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4))) begin
        tmp_41_reg_2413 <= {{p_Val2_8_2_fu_1722_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st33_fsm_11)) begin
        tmp_43_reg_2477 <= tmp_43_fu_1899_p1;
        tmp_8_reg_2482 <= tmp_8_fu_1903_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st31_fsm_9)) begin
        x_V_reg_2454 <= x_V_fu_1838_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten4_reg_1929 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        y_V_1_reg_2172 <= y_V_1_fu_1227_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st32_fsm_10)) begin
        y_V_reg_2467 <= y_V_fu_1860_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st29_fsm_7) & ~(1'b0 == exitcond3_fu_1807_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st29_fsm_7) & ~(1'b0 == exitcond3_fu_1807_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_98) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_130) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_140) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_152) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_166) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_30) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_488) begin
        ap_sig_cseq_ST_st29_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_188) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_504) begin
        ap_sig_cseq_ST_st30_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st30_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_513) begin
        ap_sig_cseq_ST_st31_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st31_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_527) begin
        ap_sig_cseq_ST_st32_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st32_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_541) begin
        ap_sig_cseq_ST_st33_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st33_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_592) begin
        ap_sig_cseq_ST_st34_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st34_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st29_fsm_7)) begin
        b_conv1_ce0 = 1'b1;
    end else begin
        b_conv1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        indvar_flatten3_phi_fu_434_p4 = indvar_flatten_next4_reg_1933;
    end else begin
        indvar_flatten3_phi_fu_434_p4 = indvar_flatten3_reg_430;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        indvar_flatten4_phi_fu_457_p4 = indvar_flatten_next3_reg_2010;
    end else begin
        indvar_flatten4_phi_fu_457_p4 = indvar_flatten4_reg_453;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        indvar_flatten_phi_fu_479_p4 = indvar_flatten_next_reg_2005;
    end else begin
        indvar_flatten_phi_fu_479_p4 = indvar_flatten_reg_475;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3))) begin
        input_0_V_address0 = newIndex10_fu_1422_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        input_0_V_address0 = newIndex3_fu_1361_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        input_0_V_address0 = newIndex8_fu_1303_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4))) begin
        input_0_V_address0 = newIndex5_fu_1108_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        input_0_V_address0 = newIndex_fu_984_p1;
    end else begin
        input_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            input_0_V_address1 = newIndex7_fu_1223_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            input_0_V_address1 = newIndex11_fu_1181_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            input_0_V_address1 = newIndex4_fu_1098_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            input_0_V_address1 = newIndex1_fu_1001_p1;
        end else begin
            input_0_V_address1 = 'bx;
        end
    end else begin
        input_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        input_0_V_ce0 = 1'b1;
    end else begin
        input_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)))) begin
        input_0_V_ce1 = 1'b1;
    end else begin
        input_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3))) begin
        input_1_V_address0 = newIndex10_fu_1422_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        input_1_V_address0 = newIndex3_fu_1361_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        input_1_V_address0 = newIndex8_fu_1303_p1;
    end else begin
        input_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        input_1_V_ce0 = 1'b1;
    end else begin
        input_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3))) begin
        input_2_V_address0 = newIndex10_fu_1422_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        input_2_V_address0 = newIndex3_fu_1361_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        input_2_V_address0 = newIndex8_fu_1303_p1;
    end else begin
        input_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        input_2_V_ce0 = 1'b1;
    end else begin
        input_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3))) begin
        input_3_V_address0 = newIndex10_fu_1422_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        input_3_V_address0 = newIndex3_fu_1361_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        input_3_V_address0 = newIndex8_fu_1303_p1;
    end else begin
        input_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it3)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        input_3_V_ce0 = 1'b1;
    end else begin
        input_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st34_fsm_12)) begin
        output_V_address0 = output_V_addr_1_reg_2472;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it5))) begin
        output_V_address0 = output_V_addr_2_reg_2423;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_V_address0 = tmp_2_fu_585_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st32_fsm_10)) begin
        output_V_address0 = tmp_1_fu_1889_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it4) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_V_address0 = tmp_3_fu_1791_p1;
    end else begin
        output_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st32_fsm_10) | (1'b1 == ap_sig_cseq_ST_st34_fsm_12) | ((1'b1 == ap_reg_ppiten_pp0_it4) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it5)))) begin
        output_V_ce0 = 1'b1;
    end else begin
        output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st34_fsm_12)) begin
        output_V_d0 = p_Val2_2_cast_fu_1915_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it5))) begin
        output_V_d0 = p_Val2_5_fu_1795_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_V_d0 = ap_const_lv32_0;
    end else begin
        output_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_573_p2)) | (1'b1 == ap_sig_cseq_ST_st34_fsm_12) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it5) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter4)))) begin
        output_V_we0 = 1'b1;
    end else begin
        output_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_1_phi_fu_445_p4 = t_V_1_mid2_reg_1954;
    end else begin
        t_V_1_phi_fu_445_p4 = t_V_1_reg_441;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_3_phi_fu_468_p4 = t_V_3_mid2_reg_1987;
    end else begin
        t_V_3_phi_fu_468_p4 = t_V_3_reg_464;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten4_reg_1929_pp0_iter1))) begin
        t_V_5_phi_fu_501_p4 = t_V_5_cast3_mid2_reg_2031;
    end else begin
        t_V_5_phi_fu_501_p4 = t_V_5_reg_497;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten4_reg_1929 == 1'b0))) begin
        t_V_7_phi_fu_490_p4 = y_V_1_reg_2172;
    end else begin
        t_V_7_phi_fu_490_p4 = t_V_7_reg_486;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1))) begin
        w_conv1_0_address0 = OP2_V_2_2_mid2_v_fu_1241_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        w_conv1_0_address0 = OP2_V_2_1_mid2_v_fu_1198_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        w_conv1_0_address0 = OP2_V_1_1_mid2_v_fu_1141_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4))) begin
        w_conv1_0_address0 = OP2_V_0_2_mid2_v_fu_1023_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        w_conv1_0_address0 = OP2_V_0_1_mid2_v_fu_906_p1;
    end else begin
        w_conv1_0_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        w_conv1_0_address1 = OP2_V_2_mid2_v_fu_1335_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4))) begin
        w_conv1_0_address1 = OP2_V_1_mid2_v_fu_1279_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        w_conv1_0_address1 = OP2_V_cast_mid2_v_fu_1270_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        w_conv1_0_address1 = OP2_V_1_2_mid2_v_fu_1151_p1;
    end else begin
        w_conv1_0_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it1)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)))) begin
        w_conv1_0_ce0 = 1'b1;
    end else begin
        w_conv1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        w_conv1_0_ce1 = 1'b1;
    end else begin
        w_conv1_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((1'b0 == exitcond1_fu_573_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : begin
            if (~((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b1 == ap_reg_ppiten_pp0_it4) & ~(1'b1 == ap_reg_ppiten_pp0_it3))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st29_fsm_7;
            end
        end
        ap_ST_pp0_stg1_fsm_3 : begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_4;
        end
        ap_ST_pp0_stg2_fsm_4 : begin
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_5;
        end
        ap_ST_pp0_stg3_fsm_5 : begin
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_6;
        end
        ap_ST_pp0_stg4_fsm_6 : begin
            ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
        end
        ap_ST_st29_fsm_7 : begin
            if (~(1'b0 == exitcond3_fu_1807_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st30_fsm_8;
            end
        end
        ap_ST_st30_fsm_8 : begin
            ap_NS_fsm = ap_ST_st31_fsm_9;
        end
        ap_ST_st31_fsm_9 : begin
            if (~(1'b0 == exitcond5_fu_1832_p2)) begin
                ap_NS_fsm = ap_ST_st29_fsm_7;
            end else begin
                ap_NS_fsm = ap_ST_st32_fsm_10;
            end
        end
        ap_ST_st32_fsm_10 : begin
            if ((1'b0 == exitcond_fu_1854_p2)) begin
                ap_NS_fsm = ap_ST_st33_fsm_11;
            end else begin
                ap_NS_fsm = ap_ST_st31_fsm_9;
            end
        end
        ap_ST_st33_fsm_11 : begin
            ap_NS_fsm = ap_ST_st34_fsm_12;
        end
        ap_ST_st34_fsm_12 : begin
            ap_NS_fsm = ap_ST_st32_fsm_10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP2_V_0_1_mid2_v_fu_906_p1 = OP2_V_0_1_mid2_v_v_fu_901_p2;

assign OP2_V_0_1_mid2_v_v_fu_901_p2 = (ap_const_lv9_3 + OP2_V_cast_mid2_v_v_reg_1966);

assign OP2_V_0_2_mid2_v_fu_1023_p1 = OP2_V_0_2_mid2_v_v_fu_1018_p2;

assign OP2_V_0_2_mid2_v_v_fu_1018_p2 = (ap_const_lv9_6 + OP2_V_cast_mid2_v_v_reg_1966);

assign OP2_V_1_1_mid2_v_fu_1141_p1 = OP2_V_1_1_mid2_v_v_fu_1136_p2;

assign OP2_V_1_1_mid2_v_v_fu_1136_p2 = (ap_const_lv9_4 + OP2_V_cast_mid2_v_v_reg_1966);

assign OP2_V_1_2_mid2_v_fu_1151_p1 = OP2_V_1_2_mid2_v_v_fu_1146_p2;

assign OP2_V_1_2_mid2_v_v_fu_1146_p2 = (ap_const_lv9_7 + OP2_V_cast_mid2_v_v_reg_1966);

assign OP2_V_1_mid2_v_fu_1279_p1 = OP2_V_1_mid2_v_v_fu_1274_p2;

assign OP2_V_1_mid2_v_v_fu_1274_p2 = (ap_const_lv9_1 + ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter2);

assign OP2_V_2_1_mid2_v_fu_1198_p1 = OP2_V_2_1_mid2_v_v_fu_1193_p2;

assign OP2_V_2_1_mid2_v_v_fu_1193_p2 = (ap_const_lv9_5 + OP2_V_cast_mid2_v_v_reg_1966);

assign OP2_V_2_2_mid2_v_fu_1241_p1 = OP2_V_2_2_mid2_v_v_fu_1236_p2;

assign OP2_V_2_2_mid2_v_v_fu_1236_p2 = (ap_const_lv9_8 + OP2_V_cast_mid2_v_v_reg_1966);

assign OP2_V_2_mid2_v_fu_1335_p1 = OP2_V_2_mid2_v_v_fu_1330_p2;

assign OP2_V_2_mid2_v_v_fu_1330_p2 = (ap_const_lv9_2 + ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter2);

assign OP2_V_cast_mid2159_v_v_fu_700_p3 = ((exitcond_flatten_fu_638_p2[0:0] === 1'b1) ? tmp_7_mid_fu_694_p2 : tmp_7_fu_620_p2);

assign OP2_V_cast_mid2_v_fu_1270_p1 = ap_reg_ppstg_OP2_V_cast_mid2_v_v_reg_1966_pp0_iter2;

assign OP2_V_cast_mid2_v_v_fu_806_p3 = ((exitcond_flatten_mid_fu_726_p2[0:0] === 1'b1) ? tmp_7_mid1_fu_800_p2 : OP2_V_cast_mid2159_v_v_fu_700_p3);

always @ (*) begin
    ap_sig_130 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_140 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_152 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_1575 = ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten4_reg_1929 == 1'b0));
end

always @ (*) begin
    ap_sig_166 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_188 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_30 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_488 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_504 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_513 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_527 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_541 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_592 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

always @ (*) begin
    ap_sig_98 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

assign arrayNo2_fu_1340_p1 = $signed(tmp_34_reg_2242);

assign arrayNo8_fu_1401_p1 = $signed(tmp_38_reg_2267);

assign arrayNo_fu_1443_p1 = $signed(tmp_39_reg_2302);

assign b_conv1_address0 = tmp_4_fu_1819_p1;

assign biased_V_fu_1894_p2 = (output_V_q0 + p_Val2_3_cast_reg_2446);

assign exitcond1_fu_573_p2 = ((t_V_reg_419 == ap_const_lv10_320) ? 1'b1 : 1'b0);

assign exitcond3_fu_1807_p2 = ((t_V_2_reg_509 == ap_const_lv6_20) ? 1'b1 : 1'b0);

assign exitcond4_fu_708_p2 = ((t_V_7_phi_fu_490_p4 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign exitcond5_fu_1832_p2 = ((t_V_4_reg_532 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign exitcond7_mid2_fu_826_p2 = (exitcond7_mid_fu_714_p2 & not_exitcond_flatten_mid_fu_820_p2);

assign exitcond7_mid_fu_714_p2 = (exitcond4_fu_708_p2 & not_exitcond_flatten_fu_644_p2);

assign exitcond_flatten2_fu_720_p2 = ((indvar_flatten_phi_fu_479_p4 == ap_const_lv6_19) ? 1'b1 : 1'b0);

assign exitcond_flatten4_fu_626_p2 = ((indvar_flatten3_phi_fu_434_p4 == ap_const_lv10_320) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_638_p2 = ((indvar_flatten4_phi_fu_457_p4 == ap_const_lv6_19) ? 1'b1 : 1'b0);

assign exitcond_flatten_mid_fu_726_p2 = (exitcond_flatten2_fu_720_p2 & not_exitcond_flatten_fu_644_p2);

assign exitcond_flatten_not_fu_814_p2 = (exitcond_flatten2_fu_720_p2 ^ 1'b1);

assign exitcond_fu_1854_p2 = ((t_V_6_reg_543 == ap_const_lv3_5) ? 1'b1 : 1'b0);

assign grp_fu_1087_p0 = ($signed(tmp1_cast19_cast_reg_2036) + $signed(tmp_15_1_cast_cast_mid2_cast_fu_1058_p1));

assign grp_fu_962_p0 = ($signed(tmp1_cast19_cast_fu_952_p1) + $signed(t_V_5_cast24_cast_mid2_cast_fu_928_p1));

assign i_V_fu_579_p2 = (t_V_reg_419 + ap_const_lv10_1);

assign i_index_V_0_1_fu_978_p2 = (tmp1_0_1_cast_fu_972_p2 + t_V_5_cast3_mid2_cast_fu_924_p1);

assign i_index_V_0_2_fu_995_p2 = (tmp1_0_2_cast_fu_989_p2 + t_V_5_cast3_mid2_cast_fu_924_p1);

assign i_index_V_1_1_fu_1093_p2 = (tmp1_0_1_cast_reg_2048 + tmp_15_1_cast_mid2_cast_fu_1054_p1);

assign i_index_V_1_2_fu_1103_p2 = (tmp1_0_2_cast_reg_2059 + tmp_15_1_cast_mid2_cast_fu_1054_p1);

assign i_index_V_1_fu_1082_p2 = ($signed(tmp1_cast19_cast_reg_2036) + $signed(tmp_15_1_cast_cast_mid2_cast_fu_1058_p1));

assign i_index_V_2_1_fu_1118_p2 = (tmp1_0_1_cast_reg_2048 + tmp_15_2_cast_mid2_cast_fu_1074_p1);

assign i_index_V_2_2_fu_1123_p2 = (tmp1_0_2_cast_reg_2059 + tmp_15_2_cast_mid2_cast_fu_1074_p1);

assign i_index_V_2_fu_1113_p2 = ($signed(tmp1_cast19_cast_reg_2036) + $signed(tmp_15_2_cast_cast_mid2_cast_fu_1078_p1));

assign i_index_V_fu_956_p2 = ($signed(tmp1_cast19_cast_fu_952_p1) + $signed(t_V_5_cast24_cast_mid2_cast_fu_928_p1));

assign index_V_fu_1884_p2 = (tmp6_reg_2459 + tmp5_cast_fu_1880_p1);

assign indvar_flatten40_op_fu_880_p2 = (ap_const_lv6_1 + indvar_flatten4_phi_fu_457_p4);

assign indvar_flatten_next3_fu_886_p3 = ((exitcond_flatten_fu_638_p2[0:0] === 1'b1) ? ap_const_lv6_1 : indvar_flatten40_op_fu_880_p2);

assign indvar_flatten_next4_fu_632_p2 = (ap_const_lv10_1 + indvar_flatten3_phi_fu_434_p4);

assign indvar_flatten_next_fu_872_p3 = ((tmp_24_fu_752_p2[0:0] === 1'b1) ? ap_const_lv6_1 : indvar_flatten_op_fu_866_p2);

assign indvar_flatten_op_fu_866_p2 = (ap_const_lv6_1 + indvar_flatten_phi_fu_479_p4);

assign m_V_fu_746_p2 = (exitcond_flatten_fu_638_p2 | t_V_3_not_fu_740_p2);

assign mul3_fu_1287_p1 = mul3_fu_1287_p10;

assign mul3_fu_1287_p10 = ap_reg_ppstg_i_index_V_reg_2042_pp0_iter2;

assign mul3_fu_1287_p2 = (ap_const_lv20_290 * mul3_fu_1287_p1);

assign mul4_fu_1314_p1 = mul4_fu_1314_p10;

assign mul4_fu_1314_p10 = ap_reg_ppstg_i_index_V_1_reg_2075_pp0_iter2;

assign mul4_fu_1314_p2 = (ap_const_lv20_290 * mul4_fu_1314_p1);

assign mul_fu_1372_p1 = mul_fu_1372_p10;

assign mul_fu_1372_p10 = ap_reg_ppstg_i_index_V_2_reg_2091_pp0_iter2;

assign mul_fu_1372_p2 = (ap_const_lv20_290 * mul_fu_1372_p1);

assign n_V_1_fu_1813_p2 = (t_V_2_reg_509 + ap_const_lv6_1);

assign n_V_fu_656_p2 = (ap_const_lv6_1 + t_V_1_phi_fu_445_p4);

assign newIndex10_fu_1422_p1 = grp_fu_1176_p2;

assign newIndex11_fu_1181_p1 = i_index_V_2_1_reg_2097;

assign newIndex1_fu_1001_p1 = i_index_V_0_2_fu_995_p2;

assign newIndex3_fu_1361_p1 = grp_fu_1087_p2;

assign newIndex4_fu_1098_p1 = i_index_V_1_1_fu_1093_p2;

assign newIndex5_fu_1108_p1 = i_index_V_1_2_fu_1103_p2;

assign newIndex7_fu_1223_p1 = i_index_V_2_2_reg_2102;

assign newIndex8_fu_1303_p1 = grp_fu_962_p2;

assign newIndex_fu_984_p1 = i_index_V_0_1_fu_978_p2;

assign next_mul_fu_1801_p2 = (phi_mul_reg_520 + ap_const_lv10_19);

assign not_exitcond_flatten1_fu_662_p2 = (exitcond_flatten_fu_638_p2 ^ 1'b1);

assign not_exitcond_flatten_fu_644_p2 = (exitcond_flatten_fu_638_p2 ^ 1'b1);

assign not_exitcond_flatten_mid_fu_820_p2 = (exitcond_flatten_fu_638_p2 | exitcond_flatten_not_fu_814_p2);

assign o_index_V_fu_1679_p2 = (tmp3_cast_fu_1675_p1 + tmp4_mid2_fu_1599_p3);

assign p_1_fu_1481_p1 = p_1_fu_1481_p10;

assign p_1_fu_1481_p10 = ap_reg_ppstg_t_V_1_reg_441_pp0_iter3;

assign p_1_fu_1481_p2 = (ap_const_lv10_19 * p_1_fu_1481_p1);

assign p_1_mid1_fu_1510_p1 = p_1_mid1_fu_1510_p10;

assign p_1_mid1_fu_1510_p10 = ap_reg_ppstg_n_V_reg_1944_pp0_iter4;

assign p_1_mid1_fu_1510_p2 = (ap_const_lv10_19 * p_1_mid1_fu_1510_p1);

assign p_1_mid2_fu_1573_p3 = ((ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter4[0:0] === 1'b1) ? p_1_mid1_reg_2382 : p_1_reg_2367);

assign p_3_cast_mid2_cast_fu_770_p1 = p_3_cast_mid2_fu_762_p3;

assign p_3_cast_mid2_fu_762_p3 = ((exitcond_flatten_mid_fu_726_p2[0:0] === 1'b1) ? m_V_fu_746_p2 : p_3_cast_mid_fu_668_p2);

assign p_3_cast_mid_fu_668_p2 = (t_V_3_phi_fu_468_p4 & not_exitcond_flatten1_fu_662_p2);

assign p_Val2_2_cast_fu_1915_p1 = p_Val2_2_s_fu_1909_p3;

assign p_Val2_2_s_fu_1909_p3 = ((tmp_8_reg_2482[0:0] === 1'b1) ? tmp_43_reg_2477 : ap_const_lv31_0);

assign p_Val2_3_cast_fu_1824_p1 = b_conv1_q0;

assign p_Val2_5_fu_1795_p2 = (sum_V_2_2_reg_2418 + output_V_q0);

assign p_Val2_7_0_1_cast_fu_1516_p1 = $signed(ap_reg_ppstg_p_Val2_7_0_1_reg_2202_pp0_iter3);

assign p_Val2_7_0_2_cast_fu_1536_p1 = $signed(ap_reg_ppstg_p_Val2_7_0_2_reg_2207_pp0_iter3);

assign p_Val2_7_1_1_cast_fu_1625_p1 = $signed(ap_reg_ppstg_p_Val2_7_1_1_reg_2212_pp0_iter3);

assign p_Val2_7_1_2_cast_fu_1685_p1 = $signed(ap_reg_ppstg_p_Val2_7_1_2_reg_2217_pp0_iter3);

assign p_Val2_7_1_cast_fu_1609_p1 = $signed(p_Val2_7_1_reg_2388);

assign p_Val2_7_2_1_cast_fu_1738_p1 = $signed(ap_reg_ppstg_p_Val2_7_2_1_reg_2222_pp0_iter4);

assign p_Val2_7_2_2_cast_fu_1754_p1 = $signed(ap_reg_ppstg_p_Val2_7_2_2_reg_2232_pp0_iter4);

assign p_Val2_7_2_cast_fu_1701_p1 = $signed(p_Val2_7_2_reg_2403);

assign p_Val2_8_0_1_fu_1530_p2 = ($signed(p_Val2_7_0_1_cast_fu_1516_p1) + $signed(tmp_20_0_1_fu_1526_p1));

assign p_Val2_8_0_2_fu_1557_p2 = ($signed(p_Val2_7_0_2_cast_fu_1536_p1) + $signed(tmp_20_0_2_fu_1549_p3));

assign p_Val2_8_1_1_fu_1646_p2 = ($signed(p_Val2_7_1_1_cast_fu_1625_p1) + $signed(tmp_20_1_1_fu_1638_p3));

assign p_Val2_8_1_2_fu_1695_p2 = ($signed(p_Val2_7_1_2_cast_fu_1685_p1) + $signed(tmp_20_1_2_fu_1688_p3));

assign p_Val2_8_1_fu_1619_p2 = ($signed(p_Val2_7_1_cast_fu_1609_p1) + $signed(tmp_20_1_fu_1612_p3));

assign p_Val2_8_2_1_fu_1748_p2 = ($signed(p_Val2_7_2_1_cast_fu_1738_p1) + $signed(tmp_20_2_1_fu_1741_p3));

assign p_Val2_8_2_2_fu_1775_p2 = ($signed(p_Val2_7_2_2_cast_fu_1754_p1) + $signed(tmp_20_2_2_fu_1767_p3));

assign p_Val2_8_2_fu_1722_p2 = ($signed(p_Val2_7_2_cast_fu_1701_p1) + $signed(tmp_20_2_fu_1714_p3));

assign p_shl2_fu_1662_p3 = {{ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter4}, {ap_const_lv2_0}};

assign p_shl3_cast_fu_942_p1 = p_shl3_fu_935_p3;

assign p_shl3_fu_935_p3 = {{tmp2_reg_1999}, {ap_const_lv3_0}};

assign p_shl4_fu_1866_p3 = {{t_V_6_reg_543}, {ap_const_lv2_0}};

assign p_shl_cast_fu_616_p1 = p_shl_fu_608_p3;

assign p_shl_cast_mid1_fu_796_p1 = p_shl_mid1_fu_788_p3;

assign p_shl_cast_mid_fu_690_p1 = p_shl_mid_fu_682_p3;

assign p_shl_fu_608_p3 = {{tmp_29_fu_604_p1}, {ap_const_lv3_0}};

assign p_shl_mid1_fu_788_p3 = {{tmp_32_fu_784_p1}, {ap_const_lv3_0}};

assign p_shl_mid_fu_682_p3 = {{tmp_31_fu_678_p1}, {ap_const_lv3_0}};

assign t_V_1_mid2_fu_732_p3 = ((exitcond_flatten_fu_638_p2[0:0] === 1'b1) ? n_V_fu_656_p2 : t_V_1_phi_fu_445_p4);

assign t_V_3_cast_fu_590_p1 = t_V_3_phi_fu_468_p4;

assign t_V_3_cast_mid1_fu_758_p1 = m_V_fu_746_p2;

assign t_V_3_mid2_fu_832_p3 = ((exitcond_flatten_mid_fu_726_p2[0:0] === 1'b1) ? m_V_fu_746_p2 : t_V_3_mid_fu_650_p2);

assign t_V_3_mid_fu_650_p2 = (t_V_3_phi_fu_468_p4 & not_exitcond_flatten_fu_644_p2);

assign t_V_3_not_fu_740_p2 = (t_V_3_phi_fu_468_p4 ^ 1'b1);

assign t_V_4_cast8_fu_1828_p1 = t_V_4_reg_532;

assign t_V_5_cast24_cast_mid2_cast_fu_928_p1 = t_V_5_cast3_mid2_fu_917_p3;

assign t_V_5_cast3_mid2_cast_fu_924_p1 = t_V_5_cast3_mid2_fu_917_p3;

assign t_V_5_cast3_mid2_fu_917_p3 = ((exitcond7_mid2_reg_1979[0:0] === 1'b1) ? x_V_2_dup_fu_911_p2 : t_V_5_mid_fu_894_p3);

assign t_V_5_cast_fu_1487_p1 = ap_reg_ppstg_t_V_5_reg_497_pp0_iter3;

assign t_V_5_cast_mid1_fu_1590_p1 = ap_reg_ppstg_x_V_2_dup_reg_2026_pp0_iter4;

assign t_V_5_mid_fu_894_p3 = ((tmp_24_reg_1959[0:0] === 1'b1) ? ap_const_lv3_0 : t_V_5_phi_fu_501_p4);

assign t_V_6_cast7_fu_1850_p1 = t_V_6_reg_543;

assign t_V_7_cast_fu_1606_p1 = ap_reg_ppstg_t_V_7_mid2_reg_1992_pp0_iter4;

assign t_V_7_mid2_fu_852_p3 = ((tmp_33_fu_846_p2[0:0] === 1'b1) ? ap_const_lv3_0 : t_V_7_phi_fu_490_p4);

assign tmp1_0_1_cast_fu_972_p2 = (ap_const_lv6_7 + tmp_35_fu_968_p1);

assign tmp1_0_2_cast_fu_989_p2 = (ap_const_lv6_E + tmp_35_fu_968_p1);

assign tmp1_cast19_cast_fu_952_p1 = $signed(tmp1_fu_946_p2);

assign tmp1_fu_946_p2 = (p_shl3_cast_fu_942_p1 - tmp2_cast1_fu_932_p1);

assign tmp2_cast1_fu_932_p1 = tmp2_reg_1999;

assign tmp2_fu_860_p2 = (p_3_cast_mid2_cast_fu_770_p1 + t_V_7_mid2_fu_852_p3);

assign tmp3_cast_fu_1675_p1 = tmp3_fu_1669_p2;

assign tmp3_fu_1669_p2 = (t_V_7_cast_fu_1606_p1 + p_shl2_fu_1662_p3);

assign tmp4_fu_1491_p2 = (p_1_fu_1481_p2 + t_V_5_cast_fu_1487_p1);

assign tmp4_mid1_fu_1593_p2 = (p_1_mid2_fu_1573_p3 + t_V_5_cast_mid1_fu_1590_p1);

assign tmp4_mid2_fu_1599_p3 = ((ap_reg_ppstg_exitcond7_mid2_reg_1979_pp0_iter4[0:0] === 1'b1) ? tmp4_mid1_fu_1593_p2 : tmp4_mid3_fu_1583_p3);

assign tmp4_mid3_fu_1583_p3 = ((ap_reg_ppstg_exitcond_flatten_mid_reg_1949_pp0_iter4[0:0] === 1'b1) ? p_1_mid2_fu_1573_p3 : tmp4_mid_fu_1578_p3);

assign tmp4_mid_fu_1578_p3 = ((ap_reg_ppstg_exitcond_flatten_reg_1938_pp0_iter4[0:0] === 1'b1) ? p_1_mid1_reg_2382 : tmp4_reg_2372);

assign tmp5_cast_fu_1880_p1 = tmp5_fu_1874_p2;

assign tmp5_fu_1874_p2 = (p_shl4_fu_1866_p3 + t_V_6_cast7_fu_1850_p1);

assign tmp6_fu_1844_p2 = (t_V_4_cast8_fu_1828_p1 + phi_mul_reg_520);

assign tmp_10_fu_1408_p5 = $unsigned(arrayNo8_fu_1401_p1);

assign tmp_11_fu_1450_p5 = $unsigned(arrayNo_fu_1443_p1);

assign tmp_15_1_cast_cast_mid2_cast_fu_1058_p1 = tmp_15_1_cast_mid2_fu_1047_p3;

assign tmp_15_1_cast_mid2_cast_fu_1054_p1 = tmp_15_1_cast_mid2_fu_1047_p3;

assign tmp_15_1_cast_mid2_fu_1047_p3 = ((exitcond7_mid2_reg_1979[0:0] === 1'b1) ? x_V_2_mid1_fu_1042_p2 : tmp_15_1_cast_mid_fu_1028_p3);

assign tmp_15_1_cast_mid_fu_1028_p3 = ((tmp_24_reg_1959[0:0] === 1'b1) ? ap_const_lv3_1 : x_V_2_fu_1006_p2);

assign tmp_15_2_cast_cast_mid2_cast_fu_1078_p1 = tmp_15_2_cast_mid2_fu_1067_p3;

assign tmp_15_2_cast_mid2_cast_fu_1074_p1 = tmp_15_2_cast_mid2_fu_1067_p3;

assign tmp_15_2_cast_mid2_fu_1067_p3 = ((exitcond7_mid2_reg_1979[0:0] === 1'b1) ? tmp_15_2_mid1_fu_1062_p2 : tmp_15_2_cast_mid_fu_1035_p3);

assign tmp_15_2_cast_mid_fu_1035_p3 = ((tmp_24_reg_1959[0:0] === 1'b1) ? ap_const_lv3_2 : tmp_15_2_fu_1012_p2);

assign tmp_15_2_fu_1012_p2 = (ap_const_lv3_2 + t_V_5_reg_497);

assign tmp_15_2_mid1_fu_1062_p2 = (ap_const_lv3_3 + t_V_5_mid_reg_2015);

assign tmp_1_fu_1889_p1 = index_V_fu_1884_p2;

assign tmp_20_0_1_fu_1526_p1 = $signed(tmp_37_fu_1519_p3);

assign tmp_20_0_2_fu_1549_p3 = {{tmp_26_fu_1539_p4}, {ap_const_lv30_0}};

assign tmp_20_1_1_fu_1638_p3 = {{tmp_28_fu_1628_p4}, {ap_const_lv30_0}};

assign tmp_20_1_2_fu_1688_p3 = {{tmp_30_reg_2398}, {ap_const_lv30_0}};

assign tmp_20_1_fu_1612_p3 = {{tmp_27_reg_2393}, {ap_const_lv30_0}};

assign tmp_20_2_1_fu_1741_p3 = {{tmp_41_reg_2413}, {ap_const_lv30_0}};

assign tmp_20_2_2_fu_1767_p3 = {{tmp_42_fu_1757_p4}, {ap_const_lv30_0}};

assign tmp_20_2_fu_1714_p3 = {{tmp_40_fu_1704_p4}, {ap_const_lv30_0}};

assign tmp_24_fu_752_p2 = (exitcond_flatten_mid_fu_726_p2 | exitcond_flatten_fu_638_p2);

assign tmp_25_fu_840_p2 = (exitcond7_mid2_fu_826_p2 | exitcond_flatten_mid_fu_726_p2);

assign tmp_26_fu_1539_p4 = {{p_Val2_8_0_1_fu_1530_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_28_fu_1628_p4 = {{p_Val2_8_1_fu_1619_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_29_fu_604_p1 = tmp_6_fu_594_p2[4:0];

assign tmp_2_fu_585_p1 = t_V_reg_419;

assign tmp_31_fu_678_p1 = n_V_fu_656_p2[4:0];

assign tmp_32_fu_784_p1 = tmp_6_mid1_fu_774_p2[4:0];

assign tmp_33_fu_846_p2 = (tmp_25_fu_840_p2 | exitcond_flatten_fu_638_p2);

assign tmp_35_fu_968_p1 = tmp1_fu_946_p2[5:0];

assign tmp_37_fu_1519_p3 = {{tmp_36_reg_2377}, {ap_const_lv30_0}};

assign tmp_3_fu_1791_p1 = o_index_V_reg_2408;

assign tmp_40_fu_1704_p4 = {{p_Val2_8_1_2_fu_1695_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_42_fu_1757_p4 = {{p_Val2_8_2_1_fu_1748_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_43_fu_1899_p1 = biased_V_fu_1894_p2[30:0];

assign tmp_4_fu_1819_p1 = t_V_2_reg_509;

assign tmp_6_cast2_fu_600_p1 = tmp_6_fu_594_p2;

assign tmp_6_cast2_mid1_fu_780_p1 = tmp_6_mid1_fu_774_p2;

assign tmp_6_cast2_mid_fu_674_p1 = n_V_fu_656_p2;

assign tmp_6_fu_594_p2 = (t_V_3_cast_fu_590_p1 + t_V_1_phi_fu_445_p4);

assign tmp_6_mid1_fu_774_p2 = (t_V_3_cast_mid1_fu_758_p1 + t_V_1_mid2_fu_732_p3);

assign tmp_7_fu_620_p2 = (tmp_6_cast2_fu_600_p1 + p_shl_cast_fu_616_p1);

assign tmp_7_mid1_fu_800_p2 = (tmp_6_cast2_mid1_fu_780_p1 + p_shl_cast_mid1_fu_796_p1);

assign tmp_7_mid_fu_694_p2 = (tmp_6_cast2_mid_fu_674_p1 + p_shl_cast_mid_fu_690_p1);

assign tmp_8_fu_1903_p2 = (($signed(biased_V_fu_1894_p2) > $signed(32'b00000000000000000000000000000000)) ? 1'b1 : 1'b0);

assign tmp_s_fu_1347_p5 = $unsigned(arrayNo2_fu_1340_p1);

assign x_V_2_dup_fu_911_p2 = (ap_const_lv3_1 + t_V_5_mid_fu_894_p3);

assign x_V_2_fu_1006_p2 = (ap_const_lv3_1 + t_V_5_reg_497);

assign x_V_2_mid1_fu_1042_p2 = (ap_const_lv3_2 + t_V_5_mid_reg_2015);

assign x_V_fu_1838_p2 = (t_V_4_reg_532 + ap_const_lv3_1);

assign y_V_1_fu_1227_p2 = (ap_const_lv3_1 + t_V_7_mid2_reg_1992);

assign y_V_fu_1860_p2 = (t_V_6_reg_543 + ap_const_lv3_1);

always @ (posedge ap_clk) begin
    p_Val2_3_cast_reg_2446[31:28] <= 4'b0000;
end

endmodule //dut_perform_conv
