// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_cnn_xcel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V,
        output_V_address0,
        output_V_ce0,
        output_V_we0,
        output_V_d0
);

parameter    ap_ST_st1_fsm_0 = 14'b1;
parameter    ap_ST_st2_fsm_1 = 14'b10;
parameter    ap_ST_st3_fsm_2 = 14'b100;
parameter    ap_ST_st4_fsm_3 = 14'b1000;
parameter    ap_ST_st5_fsm_4 = 14'b10000;
parameter    ap_ST_st6_fsm_5 = 14'b100000;
parameter    ap_ST_st7_fsm_6 = 14'b1000000;
parameter    ap_ST_st8_fsm_7 = 14'b10000000;
parameter    ap_ST_st9_fsm_8 = 14'b100000000;
parameter    ap_ST_st10_fsm_9 = 14'b1000000000;
parameter    ap_ST_st11_fsm_10 = 14'b10000000000;
parameter    ap_ST_st12_fsm_11 = 14'b100000000000;
parameter    ap_ST_st13_fsm_12 = 14'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 14'b10000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv6_31 = 6'b110001;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv30_0 = 30'b000000000000000000000000000000;
parameter    ap_const_lv10_240 = 10'b1001000000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_17 = 32'b10111;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv8_E2 = 8'b11100010;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [48:0] input_V;
output  [9:0] output_V_address0;
output   output_V_ce0;
output   output_V_we0;
output  [31:0] output_V_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_V_ce0;
reg output_V_we0;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_31;
wire   [5:0] i_fu_200_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_56;
wire   [9:0] i_2_fu_253_p2;
reg   [9:0] i_2_reg_356;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_65;
wire   [0:0] exitcond_fu_247_p2;
wire   [31:0] mem_conv1_V_load_phi_fu_279_p3;
reg   [31:0] mem_conv1_V_load_phi_reg_371;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_82;
wire   [0:0] tmp_7_fu_287_p2;
reg   [0:0] tmp_7_reg_376;
wire   [31:0] p_Result_s_fu_313_p5;
reg   [31:0] p_Result_s_reg_381;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_93;
reg   [8:0] mem_conv1_0_V_address0;
reg    mem_conv1_0_V_ce0;
reg    mem_conv1_0_V_we0;
reg   [31:0] mem_conv1_0_V_d0;
wire   [31:0] mem_conv1_0_V_q0;
reg    mem_conv1_0_V_ce1;
wire   [31:0] mem_conv1_0_V_q1;
reg   [8:0] mem_conv1_1_V_address0;
reg    mem_conv1_1_V_ce0;
reg    mem_conv1_1_V_we0;
reg   [31:0] mem_conv1_1_V_d0;
wire   [31:0] mem_conv1_1_V_q0;
reg    mem_conv1_1_V_ce1;
wire   [31:0] mem_conv1_1_V_q1;
reg   [9:0] mem_conv2_V_address0;
reg    mem_conv2_V_ce0;
wire   [31:0] mem_conv2_V_q0;
reg    mem_conv2_V_ce1;
wire   [31:0] mem_conv2_V_q1;
wire    grp_dut_perform_conv_fu_161_ap_start;
wire    grp_dut_perform_conv_fu_161_ap_done;
wire    grp_dut_perform_conv_fu_161_ap_idle;
wire    grp_dut_perform_conv_fu_161_ap_ready;
wire   [8:0] grp_dut_perform_conv_fu_161_input_0_V_address0;
wire    grp_dut_perform_conv_fu_161_input_0_V_ce0;
wire   [8:0] grp_dut_perform_conv_fu_161_input_0_V_address1;
wire    grp_dut_perform_conv_fu_161_input_0_V_ce1;
wire   [8:0] grp_dut_perform_conv_fu_161_input_1_V_address0;
wire    grp_dut_perform_conv_fu_161_input_1_V_ce0;
wire   [8:0] grp_dut_perform_conv_fu_161_input_1_V_address1;
wire    grp_dut_perform_conv_fu_161_input_1_V_ce1;
wire   [9:0] grp_dut_perform_conv_fu_161_output_V_address0;
wire    grp_dut_perform_conv_fu_161_output_V_ce0;
wire    grp_dut_perform_conv_fu_161_output_V_we0;
wire   [31:0] grp_dut_perform_conv_fu_161_output_V_d0;
wire    grp_dut_perform_conv_1_fu_176_ap_start;
wire    grp_dut_perform_conv_1_fu_176_ap_done;
wire    grp_dut_perform_conv_1_fu_176_ap_idle;
wire    grp_dut_perform_conv_1_fu_176_ap_ready;
wire   [9:0] grp_dut_perform_conv_1_fu_176_input_V_address0;
wire    grp_dut_perform_conv_1_fu_176_input_V_ce0;
wire   [9:0] grp_dut_perform_conv_1_fu_176_input_V_address1;
wire    grp_dut_perform_conv_1_fu_176_input_V_ce1;
wire   [8:0] grp_dut_perform_conv_1_fu_176_output_0_V_address0;
wire    grp_dut_perform_conv_1_fu_176_output_0_V_ce0;
wire    grp_dut_perform_conv_1_fu_176_output_0_V_we0;
wire   [31:0] grp_dut_perform_conv_1_fu_176_output_0_V_d0;
wire   [8:0] grp_dut_perform_conv_1_fu_176_output_1_V_address0;
wire    grp_dut_perform_conv_1_fu_176_output_1_V_ce0;
wire    grp_dut_perform_conv_1_fu_176_output_1_V_we0;
wire   [31:0] grp_dut_perform_conv_1_fu_176_output_1_V_d0;
reg   [5:0] bvh_d_index_reg_138;
wire   [0:0] exitcond1_fu_194_p2;
reg   [9:0] i2_reg_149;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_194;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_204;
reg    ap_reg_grp_dut_perform_conv_fu_161_ap_start;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_215;
reg    ap_reg_grp_dut_perform_conv_1_fu_176_ap_start;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_326;
wire   [63:0] newIndex35_fu_241_p1;
wire   [63:0] newIndex3_fu_269_p1;
wire   [63:0] tmp_6_fu_325_p1;
wire   [0:0] tmp_58_fu_227_p1;
wire   [31:0] tmp_5_cast_fu_221_p1;
reg    ap_sig_cseq_ST_st8_fsm_7;
reg    ap_sig_377;
wire   [31:0] index_assign_cast2_fu_190_p1;
wire   [0:0] tmp_fu_206_p3;
wire   [30:0] tmp_s_fu_213_p3;
wire   [4:0] newIndex8_fu_231_p4;
wire   [8:0] newIndex_fu_259_p4;
wire   [0:0] tmp_59_fu_275_p1;
wire   [31:0] grp_fu_187_p1;
wire   [31:0] res_V_1_fu_293_p1;
wire   [7:0] exp_V_fu_297_p4;
wire   [7:0] exp_V_2_fu_307_p2;
reg   [13:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'b1;
#0 ap_reg_grp_dut_perform_conv_fu_161_ap_start = 1'b0;
#0 ap_reg_grp_dut_perform_conv_1_fu_176_ap_start = 1'b0;
end

dut_cnn_xcel_mem_conv1_0_V #(
    .DataWidth( 32 ),
    .AddressRange( 400 ),
    .AddressWidth( 9 ))
mem_conv1_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv1_0_V_address0),
    .ce0(mem_conv1_0_V_ce0),
    .we0(mem_conv1_0_V_we0),
    .d0(mem_conv1_0_V_d0),
    .q0(mem_conv1_0_V_q0),
    .address1(grp_dut_perform_conv_fu_161_input_0_V_address1),
    .ce1(mem_conv1_0_V_ce1),
    .q1(mem_conv1_0_V_q1)
);

dut_cnn_xcel_mem_conv1_0_V #(
    .DataWidth( 32 ),
    .AddressRange( 400 ),
    .AddressWidth( 9 ))
mem_conv1_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv1_1_V_address0),
    .ce0(mem_conv1_1_V_ce0),
    .we0(mem_conv1_1_V_we0),
    .d0(mem_conv1_1_V_d0),
    .q0(mem_conv1_1_V_q0),
    .address1(grp_dut_perform_conv_fu_161_input_1_V_address1),
    .ce1(mem_conv1_1_V_ce1),
    .q1(mem_conv1_1_V_q1)
);

dut_cnn_xcel_mem_conv2_V #(
    .DataWidth( 32 ),
    .AddressRange( 800 ),
    .AddressWidth( 10 ))
mem_conv2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(mem_conv2_V_address0),
    .ce0(mem_conv2_V_ce0),
    .we0(grp_dut_perform_conv_fu_161_output_V_we0),
    .d0(grp_dut_perform_conv_fu_161_output_V_d0),
    .q0(mem_conv2_V_q0),
    .address1(grp_dut_perform_conv_1_fu_176_input_V_address1),
    .ce1(mem_conv2_V_ce1),
    .q1(mem_conv2_V_q1)
);

dut_perform_conv grp_dut_perform_conv_fu_161(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dut_perform_conv_fu_161_ap_start),
    .ap_done(grp_dut_perform_conv_fu_161_ap_done),
    .ap_idle(grp_dut_perform_conv_fu_161_ap_idle),
    .ap_ready(grp_dut_perform_conv_fu_161_ap_ready),
    .input_0_V_address0(grp_dut_perform_conv_fu_161_input_0_V_address0),
    .input_0_V_ce0(grp_dut_perform_conv_fu_161_input_0_V_ce0),
    .input_0_V_q0(mem_conv1_0_V_q0),
    .input_0_V_address1(grp_dut_perform_conv_fu_161_input_0_V_address1),
    .input_0_V_ce1(grp_dut_perform_conv_fu_161_input_0_V_ce1),
    .input_0_V_q1(mem_conv1_0_V_q1),
    .input_1_V_address0(grp_dut_perform_conv_fu_161_input_1_V_address0),
    .input_1_V_ce0(grp_dut_perform_conv_fu_161_input_1_V_ce0),
    .input_1_V_q0(mem_conv1_1_V_q0),
    .input_1_V_address1(grp_dut_perform_conv_fu_161_input_1_V_address1),
    .input_1_V_ce1(grp_dut_perform_conv_fu_161_input_1_V_ce1),
    .input_1_V_q1(mem_conv1_1_V_q1),
    .output_V_address0(grp_dut_perform_conv_fu_161_output_V_address0),
    .output_V_ce0(grp_dut_perform_conv_fu_161_output_V_ce0),
    .output_V_we0(grp_dut_perform_conv_fu_161_output_V_we0),
    .output_V_d0(grp_dut_perform_conv_fu_161_output_V_d0),
    .output_V_q0(mem_conv2_V_q0)
);

dut_perform_conv_1 grp_dut_perform_conv_1_fu_176(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dut_perform_conv_1_fu_176_ap_start),
    .ap_done(grp_dut_perform_conv_1_fu_176_ap_done),
    .ap_idle(grp_dut_perform_conv_1_fu_176_ap_idle),
    .ap_ready(grp_dut_perform_conv_1_fu_176_ap_ready),
    .input_V_address0(grp_dut_perform_conv_1_fu_176_input_V_address0),
    .input_V_ce0(grp_dut_perform_conv_1_fu_176_input_V_ce0),
    .input_V_q0(mem_conv2_V_q0),
    .input_V_address1(grp_dut_perform_conv_1_fu_176_input_V_address1),
    .input_V_ce1(grp_dut_perform_conv_1_fu_176_input_V_ce1),
    .input_V_q1(mem_conv2_V_q1),
    .output_0_V_address0(grp_dut_perform_conv_1_fu_176_output_0_V_address0),
    .output_0_V_ce0(grp_dut_perform_conv_1_fu_176_output_0_V_ce0),
    .output_0_V_we0(grp_dut_perform_conv_1_fu_176_output_0_V_we0),
    .output_0_V_d0(grp_dut_perform_conv_1_fu_176_output_0_V_d0),
    .output_0_V_q0(mem_conv1_0_V_q0),
    .output_1_V_address0(grp_dut_perform_conv_1_fu_176_output_1_V_address0),
    .output_1_V_ce0(grp_dut_perform_conv_1_fu_176_output_1_V_ce0),
    .output_1_V_we0(grp_dut_perform_conv_1_fu_176_output_1_V_we0),
    .output_1_V_d0(grp_dut_perform_conv_1_fu_176_output_1_V_d0),
    .output_1_V_q0(mem_conv1_1_V_q0)
);

dut_sitofp_32ns_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
dut_sitofp_32ns_32_6_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(mem_conv1_V_load_phi_reg_371),
    .ce(1'b1),
    .dout(grp_fu_187_p1)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dut_perform_conv_1_fu_176_ap_start <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_st4_fsm_3)) begin
            ap_reg_grp_dut_perform_conv_1_fu_176_ap_start <= 1'b1;
        end else if ((1'b1 == grp_dut_perform_conv_1_fu_176_ap_ready)) begin
            ap_reg_grp_dut_perform_conv_1_fu_176_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_grp_dut_perform_conv_fu_161_ap_start <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_194_p2))) begin
            ap_reg_grp_dut_perform_conv_fu_161_ap_start <= 1'b1;
        end else if ((1'b1 == grp_dut_perform_conv_fu_161_ap_ready)) begin
            ap_reg_grp_dut_perform_conv_fu_161_ap_start <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2))) begin
        bvh_d_index_reg_138 <= i_fu_200_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        bvh_d_index_reg_138 <= ap_const_lv6_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        i2_reg_149 <= i_2_reg_356;
    end else if (((1'b1 == ap_sig_cseq_ST_st5_fsm_4) & ~(1'b0 == grp_dut_perform_conv_1_fu_176_ap_done))) begin
        i2_reg_149 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        i_2_reg_356 <= i_2_fu_253_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st7_fsm_6)) begin
        mem_conv1_V_load_phi_reg_371 <= mem_conv1_V_load_phi_fu_279_p3;
        tmp_7_reg_376 <= tmp_7_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st13_fsm_12) & (1'b0 == tmp_7_reg_376))) begin
        p_Result_s_reg_381 <= p_Result_s_fu_313_p5;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(exitcond_fu_247_p2 == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) & ~(exitcond_fu_247_p2 == 1'b0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_93) begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_204) begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_31) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_56) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_215) begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_326) begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_194) begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_65) begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_82) begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_377) begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st8_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & (1'b0 == tmp_58_fu_227_p1))) begin
        mem_conv1_0_V_address0 = newIndex35_fu_241_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        mem_conv1_0_V_address0 = newIndex3_fu_269_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_address0 = grp_dut_perform_conv_1_fu_176_output_0_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_0_V_address0 = grp_dut_perform_conv_fu_161_input_0_V_address0;
    end else begin
        mem_conv1_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & (1'b0 == tmp_58_fu_227_p1)))) begin
        mem_conv1_0_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_ce0 = grp_dut_perform_conv_1_fu_176_output_0_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_0_V_ce0 = grp_dut_perform_conv_fu_161_input_0_V_ce0;
    end else begin
        mem_conv1_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_0_V_ce1 = grp_dut_perform_conv_fu_161_input_0_V_ce1;
    end else begin
        mem_conv1_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & (1'b0 == tmp_58_fu_227_p1))) begin
        mem_conv1_0_V_d0 = tmp_5_cast_fu_221_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_d0 = grp_dut_perform_conv_1_fu_176_output_0_V_d0;
    end else begin
        mem_conv1_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & (1'b0 == tmp_58_fu_227_p1))) begin
        mem_conv1_0_V_we0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_0_V_we0 = grp_dut_perform_conv_1_fu_176_output_0_V_we0;
    end else begin
        mem_conv1_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & ~(1'b0 == tmp_58_fu_227_p1))) begin
        mem_conv1_1_V_address0 = newIndex35_fu_241_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        mem_conv1_1_V_address0 = newIndex3_fu_269_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_address0 = grp_dut_perform_conv_1_fu_176_output_1_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_1_V_address0 = grp_dut_perform_conv_fu_161_input_1_V_address0;
    end else begin
        mem_conv1_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st6_fsm_5) | ((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & ~(1'b0 == tmp_58_fu_227_p1)))) begin
        mem_conv1_1_V_ce0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_ce0 = grp_dut_perform_conv_1_fu_176_output_1_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_1_V_ce0 = grp_dut_perform_conv_fu_161_input_1_V_ce0;
    end else begin
        mem_conv1_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv1_1_V_ce1 = grp_dut_perform_conv_fu_161_input_1_V_ce1;
    end else begin
        mem_conv1_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & ~(1'b0 == tmp_58_fu_227_p1))) begin
        mem_conv1_1_V_d0 = tmp_5_cast_fu_221_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_d0 = grp_dut_perform_conv_1_fu_176_output_1_V_d0;
    end else begin
        mem_conv1_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_194_p2) & ~(1'b0 == tmp_58_fu_227_p1))) begin
        mem_conv1_1_V_we0 = 1'b1;
    end else if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv1_1_V_we0 = grp_dut_perform_conv_1_fu_176_output_1_V_we0;
    end else begin
        mem_conv1_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_V_address0 = grp_dut_perform_conv_1_fu_176_input_V_address0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_V_address0 = grp_dut_perform_conv_fu_161_output_V_address0;
    end else begin
        mem_conv2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_V_ce0 = grp_dut_perform_conv_1_fu_176_input_V_ce0;
    end else if ((1'b1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        mem_conv2_V_ce0 = grp_dut_perform_conv_fu_161_output_V_ce0;
    end else begin
        mem_conv2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        mem_conv2_V_ce1 = grp_dut_perform_conv_1_fu_176_input_V_ce1;
    end else begin
        mem_conv2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        output_V_ce0 = 1'b1;
    end else begin
        output_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st14_fsm_13)) begin
        output_V_we0 = 1'b1;
    end else begin
        output_V_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((1'b0 == exitcond1_fu_194_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st3_fsm_2 : begin
            if (~(1'b0 == grp_dut_perform_conv_fu_161_ap_done)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end
        end
        ap_ST_st4_fsm_3 : begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st5_fsm_4 : begin
            if (~(1'b0 == grp_dut_perform_conv_1_fu_176_ap_done)) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st6_fsm_5 : begin
            if (~(exitcond_fu_247_p2 == 1'b0)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st7_fsm_6;
            end
        end
        ap_ST_st7_fsm_6 : begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : begin
            ap_NS_fsm = ap_ST_st14_fsm_13;
        end
        ap_ST_st14_fsm_13 : begin
            ap_NS_fsm = ap_ST_st6_fsm_5;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    ap_sig_194 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_204 = (1'b1 == ap_CS_fsm[ap_const_lv32_D]);
end

always @ (*) begin
    ap_sig_215 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_31 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_326 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_377 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_56 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_65 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_82 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_93 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

assign exitcond1_fu_194_p2 = ((bvh_d_index_reg_138 == ap_const_lv6_31) ? 1'b1 : 1'b0);

assign exitcond_fu_247_p2 = ((i2_reg_149 == ap_const_lv10_240) ? 1'b1 : 1'b0);

assign exp_V_2_fu_307_p2 = ($signed(ap_const_lv8_E2) + $signed(exp_V_fu_297_p4));

assign exp_V_fu_297_p4 = {{res_V_1_fu_293_p1[ap_const_lv32_1E : ap_const_lv32_17]}};

assign grp_dut_perform_conv_1_fu_176_ap_start = ap_reg_grp_dut_perform_conv_1_fu_176_ap_start;

assign grp_dut_perform_conv_fu_161_ap_start = ap_reg_grp_dut_perform_conv_fu_161_ap_start;

assign i_2_fu_253_p2 = (i2_reg_149 + ap_const_lv10_1);

assign i_fu_200_p2 = (bvh_d_index_reg_138 + ap_const_lv6_1);

assign index_assign_cast2_fu_190_p1 = bvh_d_index_reg_138;

assign mem_conv1_V_load_phi_fu_279_p3 = ((tmp_59_fu_275_p1[0:0] === 1'b1) ? mem_conv1_1_V_q0 : mem_conv1_0_V_q0);

assign newIndex35_fu_241_p1 = newIndex8_fu_231_p4;

assign newIndex3_fu_269_p1 = newIndex_fu_259_p4;

assign newIndex8_fu_231_p4 = {{bvh_d_index_reg_138[ap_const_lv32_5 : ap_const_lv32_1]}};

assign newIndex_fu_259_p4 = {{i2_reg_149[ap_const_lv32_9 : ap_const_lv32_1]}};

assign output_V_address0 = tmp_6_fu_325_p1;

assign output_V_d0 = ((tmp_7_reg_376[0:0] === 1'b1) ? ap_const_lv32_0 : p_Result_s_reg_381);

assign p_Result_s_fu_313_p5 = {{res_V_1_fu_293_p1[32'd31 : 32'd31]}, {exp_V_2_fu_307_p2}, {res_V_1_fu_293_p1[32'd22 : 32'd0]}};

assign res_V_1_fu_293_p1 = grp_fu_187_p1;

assign tmp_58_fu_227_p1 = bvh_d_index_reg_138[0:0];

assign tmp_59_fu_275_p1 = i2_reg_149[0:0];

assign tmp_5_cast_fu_221_p1 = tmp_s_fu_213_p3;

assign tmp_6_fu_325_p1 = i2_reg_149;

assign tmp_7_fu_287_p2 = ((mem_conv1_V_load_phi_fu_279_p3 == ap_const_lv32_0) ? 1'b1 : 1'b0);

assign tmp_fu_206_p3 = input_V[index_assign_cast2_fu_190_p1];

assign tmp_s_fu_213_p3 = {{tmp_fu_206_p3}, {ap_const_lv30_0}};

endmodule //dut_cnn_xcel
