// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module dut_perform_conv_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_V_address0,
        input_V_ce0,
        input_V_q0,
        input_V_address1,
        input_V_ce1,
        input_V_q1,
        output_0_V_address0,
        output_0_V_ce0,
        output_0_V_we0,
        output_0_V_d0,
        output_0_V_q0,
        output_1_V_address0,
        output_1_V_ce0,
        output_1_V_we0,
        output_1_V_d0,
        output_1_V_q0,
        output_2_V_address0,
        output_2_V_ce0,
        output_2_V_we0,
        output_2_V_d0,
        output_2_V_q0,
        output_3_V_address0,
        output_3_V_ce0,
        output_3_V_we0,
        output_3_V_d0,
        output_3_V_q0
);

parameter    ap_ST_st1_fsm_0 = 13'b1;
parameter    ap_ST_st2_fsm_1 = 13'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 13'b100;
parameter    ap_ST_pp0_stg1_fsm_3 = 13'b1000;
parameter    ap_ST_pp0_stg2_fsm_4 = 13'b10000;
parameter    ap_ST_pp0_stg3_fsm_5 = 13'b100000;
parameter    ap_ST_pp0_stg4_fsm_6 = 13'b1000000;
parameter    ap_ST_st18_fsm_7 = 13'b10000000;
parameter    ap_ST_st19_fsm_8 = 13'b100000000;
parameter    ap_ST_st20_fsm_9 = 13'b1000000000;
parameter    ap_ST_st21_fsm_10 = 13'b10000000000;
parameter    ap_ST_st22_fsm_11 = 13'b100000000000;
parameter    ap_ST_st23_fsm_12 = 13'b1000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv32_7 = 32'b111;
parameter    ap_const_lv32_8 = 32'b1000;
parameter    ap_const_lv32_9 = 32'b1001;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv10_0 = 10'b0000000000;
parameter    ap_const_lv15_0 = 15'b000000000000000;
parameter    ap_const_lv7_0 = 7'b0000000;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv4_0 = 4'b0000;
parameter    ap_const_lv2_0 = 2'b00;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv2_2 = 2'b10;
parameter    ap_const_lv2_1 = 2'b1;
parameter    ap_const_lv2_3 = 2'b11;
parameter    ap_const_lv10_320 = 10'b1100100000;
parameter    ap_const_lv10_1 = 10'b1;
parameter    ap_const_lv5_0 = 5'b00000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv15_3 = 15'b11;
parameter    ap_const_lv15_6 = 15'b110;
parameter    ap_const_lv15_1 = 15'b1;
parameter    ap_const_lv15_4 = 15'b100;
parameter    ap_const_lv15_7 = 15'b111;
parameter    ap_const_lv15_2 = 15'b10;
parameter    ap_const_lv15_5 = 15'b101;
parameter    ap_const_lv15_8 = 15'b1000;
parameter    ap_const_lv3_2 = 3'b10;
parameter    ap_const_lv15_4800 = 15'b100100000000000;
parameter    ap_const_lv10_120 = 10'b100100000;
parameter    ap_const_lv7_1 = 7'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv4_9 = 4'b1001;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv4_1 = 4'b1;
parameter    ap_const_lv10_5 = 10'b101;
parameter    ap_const_lv10_A = 10'b1010;
parameter    ap_const_lv32_1E = 32'b11110;
parameter    ap_const_lv32_3C = 32'b111100;
parameter    ap_const_lv30_0 = 30'b000000000000000000000000000000;
parameter    ap_const_lv32_3D = 32'b111101;
parameter    ap_const_lv7_40 = 7'b1000000;
parameter    ap_const_lv31_0 = 31'b0000000000000000000000000000000;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] input_V_address0;
output   input_V_ce0;
input  [31:0] input_V_q0;
output  [9:0] input_V_address1;
output   input_V_ce1;
input  [31:0] input_V_q1;
output  [7:0] output_0_V_address0;
output   output_0_V_ce0;
output   output_0_V_we0;
output  [31:0] output_0_V_d0;
input  [31:0] output_0_V_q0;
output  [7:0] output_1_V_address0;
output   output_1_V_ce0;
output   output_1_V_we0;
output  [31:0] output_1_V_d0;
input  [31:0] output_1_V_q0;
output  [7:0] output_2_V_address0;
output   output_2_V_ce0;
output   output_2_V_we0;
output  [31:0] output_2_V_d0;
input  [31:0] output_2_V_q0;
output  [7:0] output_3_V_address0;
output   output_3_V_ce0;
output   output_3_V_we0;
output  [31:0] output_3_V_d0;
input  [31:0] output_3_V_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] input_V_address0;
reg input_V_ce0;
reg[9:0] input_V_address1;
reg input_V_ce1;
reg[7:0] output_0_V_address0;
reg output_0_V_ce0;
reg output_0_V_we0;
reg[31:0] output_0_V_d0;
reg[7:0] output_1_V_address0;
reg output_1_V_ce0;
reg output_1_V_we0;
reg[31:0] output_1_V_d0;
reg[7:0] output_2_V_address0;
reg output_2_V_ce0;
reg output_2_V_we0;
reg[31:0] output_2_V_d0;
reg[7:0] output_3_V_address0;
reg output_3_V_ce0;
reg output_3_V_we0;
reg[31:0] output_3_V_d0;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_30;
reg   [14:0] w_conv2_address0;
reg    w_conv2_ce0;
wire   [29:0] w_conv2_q0;
reg   [14:0] w_conv2_address1;
reg    w_conv2_ce1;
wire  signed [29:0] w_conv2_q1;
wire   [5:0] b_conv2_address0;
reg    b_conv2_ce0;
wire   [26:0] b_conv2_q0;
reg   [14:0] indvar_flatten1_reg_457;
reg   [6:0] t_V_1_reg_468;
reg   [9:0] indvar_flatten2_reg_479;
reg   [5:0] t_V_3_reg_490;
reg   [3:0] indvar_flatten_reg_501;
reg   [1:0] t_V_5_reg_512;
reg   [1:0] t_V_7_reg_523;
reg  signed [29:0] reg_568;
reg    ap_sig_cseq_ST_pp0_stg2_fsm_4;
reg    ap_sig_114;
reg    ap_reg_ppiten_pp0_it0;
reg    ap_reg_ppiten_pp0_it1;
reg    ap_reg_ppiten_pp0_it2;
reg   [0:0] exitcond_flatten2_reg_2194;
reg    ap_sig_cseq_ST_pp0_stg3_fsm_5;
reg    ap_sig_132;
reg    ap_sig_cseq_ST_pp0_stg4_fsm_6;
reg    ap_sig_142;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_152;
reg    ap_sig_cseq_ST_pp0_stg1_fsm_3;
reg    ap_sig_162;
reg   [0:0] ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1;
reg  signed [29:0] reg_572;
reg  signed [31:0] reg_576;
reg  signed [31:0] reg_581;
wire   [0:0] exitcond1_fu_586_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_184;
wire   [9:0] i_V_fu_592_p2;
wire   [6:0] p_shl2_fu_640_p3;
reg   [6:0] p_shl2_reg_2134;
wire   [14:0] tmp_7_fu_670_p2;
reg   [14:0] tmp_7_reg_2139;
wire   [14:0] w_index_V_0_1_fu_676_p2;
reg   [14:0] w_index_V_0_1_reg_2144;
wire   [14:0] w_index_V_0_2_fu_682_p2;
reg   [14:0] w_index_V_0_2_reg_2149;
wire   [14:0] w_index_V_1_fu_688_p2;
reg   [14:0] w_index_V_1_reg_2154;
wire   [14:0] w_index_V_1_1_fu_694_p2;
reg   [14:0] w_index_V_1_1_reg_2159;
wire   [14:0] w_index_V_1_2_fu_700_p2;
reg   [14:0] w_index_V_1_2_reg_2164;
wire   [14:0] w_index_V_2_fu_706_p2;
reg   [14:0] w_index_V_2_reg_2169;
wire   [14:0] w_index_V_2_1_fu_712_p2;
reg   [14:0] w_index_V_2_1_reg_2174;
wire   [14:0] w_index_V_2_2_fu_718_p2;
reg   [14:0] w_index_V_2_2_reg_2179;
wire   [1:0] x_V_1_fu_732_p2;
reg   [1:0] x_V_1_reg_2184;
wire   [2:0] tmp_15_2_fu_738_p2;
reg   [2:0] tmp_15_2_reg_2189;
wire   [0:0] exitcond_flatten2_fu_744_p2;
reg   [0:0] ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter2;
wire   [14:0] indvar_flatten_next2_fu_750_p2;
reg   [14:0] indvar_flatten_next2_reg_2198;
wire   [0:0] exitcond_flatten_fu_756_p2;
reg   [0:0] exitcond_flatten_reg_2203;
wire   [6:0] p_shl1_cast_mid2_v_v_v_fu_796_p3;
reg   [6:0] p_shl1_cast_mid2_v_v_v_reg_2217;
wire   [5:0] tmp_16_fu_804_p1;
reg   [5:0] tmp_16_reg_2223;
wire   [14:0] tmp_7_mid_fu_824_p2;
reg   [14:0] tmp_7_mid_reg_2228;
wire   [0:0] exitcond_flatten_mid_fu_868_p2;
reg   [0:0] exitcond_flatten_mid_reg_2241;
wire   [5:0] m_V_fu_874_p2;
reg   [5:0] m_V_reg_2255;
wire   [0:0] tmp_14_fu_880_p2;
reg   [0:0] tmp_14_reg_2260;
wire   [1:0] t_V_5_mid_fu_886_p3;
reg   [1:0] t_V_5_mid_reg_2266;
wire   [10:0] tmp_6_mid1_fu_898_p2;
reg   [10:0] tmp_6_mid1_reg_2273;
wire   [6:0] tmp4_cast_mid235_v_fu_904_p3;
reg   [6:0] tmp4_cast_mid235_v_reg_2279;
wire   [0:0] exitcond7_mid1_fu_924_p2;
reg   [0:0] exitcond7_mid1_reg_2284;
wire   [5:0] t_V_3_mid2_fu_930_p3;
reg   [5:0] t_V_3_mid2_reg_2292;
wire   [1:0] t_V_7_mid2_fu_950_p3;
reg   [1:0] t_V_7_mid2_reg_2297;
wire   [5:0] tmp3_fu_962_p2;
reg   [5:0] tmp3_reg_2303;
wire   [1:0] y_V_1_fu_968_p2;
reg   [1:0] y_V_1_reg_2308;
wire   [3:0] indvar_flatten_next_fu_980_p3;
reg   [3:0] indvar_flatten_next_reg_2313;
wire   [9:0] indvar_flatten_next1_fu_994_p3;
reg   [9:0] indvar_flatten_next1_reg_2318;
wire   [14:0] OP2_V_0_2_cast_mid2_v_v_fu_1190_p3;
reg   [14:0] OP2_V_0_2_cast_mid2_v_v_reg_2333;
wire   [14:0] OP2_V_1_cast_mid2_v_v_fu_1203_p3;
reg   [14:0] OP2_V_1_cast_mid2_v_v_reg_2338;
wire   [14:0] OP2_V_1_1_cast_mid2_v_v_fu_1216_p3;
reg   [14:0] OP2_V_1_1_cast_mid2_v_v_reg_2343;
wire   [14:0] OP2_V_1_2_cast_mid2_v_v_fu_1229_p3;
reg   [14:0] OP2_V_1_2_cast_mid2_v_v_reg_2348;
wire   [14:0] OP2_V_2_cast_mid2_v_v_fu_1242_p3;
reg   [14:0] OP2_V_2_cast_mid2_v_v_reg_2353;
wire   [14:0] OP2_V_2_1_cast_mid2_v_v_fu_1255_p3;
reg   [14:0] OP2_V_2_1_cast_mid2_v_v_reg_2358;
wire   [14:0] OP2_V_2_2_cast_mid2_v_v_fu_1268_p3;
reg   [14:0] OP2_V_2_2_cast_mid2_v_v_reg_2363;
wire   [1:0] t_V_5_cast2_mid2_fu_1296_p3;
reg   [1:0] t_V_5_cast2_mid2_reg_2368;
wire   [9:0] t_V_5_cast2_mid2_cast_fu_1302_p1;
reg   [9:0] t_V_5_cast2_mid2_cast_reg_2373;
wire   [9:0] tmp_15_1_cast_mid2_cast_fu_1322_p1;
reg   [9:0] tmp_15_1_cast_mid2_cast_reg_2379;
wire   [2:0] tmp_15_2_cast_mid2_fu_1332_p3;
reg   [2:0] tmp_15_2_cast_mid2_reg_2385;
wire   [9:0] tmp10_fu_1378_p2;
reg   [9:0] tmp10_reg_2390;
wire   [1:0] tmp_28_fu_1439_p1;
reg   [1:0] tmp_28_reg_2407;
reg   [1:0] ap_reg_ppstg_tmp_28_reg_2407_pp0_iter1;
reg   [1:0] ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2;
reg   [8:0] tmp_12_reg_2412;
reg   [8:0] ap_reg_ppstg_tmp_12_reg_2412_pp0_iter1;
reg   [8:0] ap_reg_ppstg_tmp_12_reg_2412_pp0_iter2;
wire   [9:0] tmp1_0_1_fu_1461_p2;
reg   [9:0] tmp1_0_1_reg_2427;
wire   [9:0] tmp1_0_2_fu_1476_p2;
reg   [9:0] tmp1_0_2_reg_2438;
wire   [9:0] i_index_V_2_fu_1548_p2;
reg   [9:0] i_index_V_2_reg_2489;
wire   [9:0] i_index_V_2_1_fu_1553_p2;
reg   [9:0] i_index_V_2_1_reg_2494;
wire   [9:0] i_index_V_2_2_fu_1558_p2;
reg   [9:0] i_index_V_2_2_reg_2499;
reg   [30:0] tmp_s_reg_2604;
wire   [60:0] grp_fu_1524_p2;
reg   [60:0] p_Val2_7_1_reg_2609;
wire   [60:0] grp_fu_1583_p2;
reg   [60:0] p_Val2_7_0_1_reg_2614;
wire   [60:0] grp_fu_1593_p2;
reg   [60:0] p_Val2_7_0_2_reg_2619;
reg   [31:0] tmp_22_reg_2624;
wire   [60:0] grp_fu_1623_p2;
reg   [60:0] p_Val2_7_1_1_reg_2629;
wire   [60:0] grp_fu_1633_p2;
reg   [60:0] p_Val2_7_1_2_reg_2634;
reg   [31:0] tmp_24_reg_2639;
wire   [60:0] grp_fu_1655_p2;
reg   [60:0] p_Val2_7_2_reg_2644;
wire   [60:0] grp_fu_1665_p2;
reg   [60:0] p_Val2_7_2_1_reg_2649;
reg   [31:0] tmp_26_reg_2654;
wire   [60:0] grp_fu_1679_p2;
reg   [60:0] p_Val2_7_2_2_reg_2659;
reg   [7:0] output_0_V_addr_2_reg_2664;
reg   [7:0] output_1_V_addr_2_reg_2669;
reg   [7:0] output_2_V_addr_2_reg_2674;
reg   [7:0] output_3_V_addr_2_reg_2679;
reg   [31:0] sum_V_2_2_reg_2684;
wire   [31:0] p_Val2_1_fu_1922_p6;
reg   [31:0] p_Val2_1_reg_2689;
wire   [6:0] n_V_fu_1949_p2;
reg   [6:0] n_V_reg_2697;
reg    ap_sig_cseq_ST_st18_fsm_7;
reg    ap_sig_430;
wire   [0:0] exitcond3_fu_1943_p2;
wire   [10:0] p_shl5_cast_fu_1972_p1;
reg   [10:0] p_shl5_cast_reg_2707;
reg    ap_sig_cseq_ST_st19_fsm_8;
reg    ap_sig_444;
wire   [31:0] p_Val2_1_cast_fu_1976_p1;
reg   [31:0] p_Val2_1_cast_reg_2712;
wire   [1:0] x_V_fu_1990_p2;
reg   [1:0] x_V_reg_2720;
reg    ap_sig_cseq_ST_st20_fsm_9;
reg    ap_sig_455;
wire   [10:0] tmp7_cast_fu_2002_p1;
reg   [10:0] tmp7_cast_reg_2725;
wire   [0:0] exitcond5_fu_1984_p2;
wire   [1:0] y_V_fu_2016_p2;
reg   [1:0] y_V_reg_2733;
reg    ap_sig_cseq_ST_st21_fsm_10;
reg    ap_sig_469;
wire   [1:0] tmp_30_fu_2054_p1;
reg   [1:0] tmp_30_reg_2738;
wire   [0:0] exitcond_fu_2010_p2;
reg   [7:0] output_0_V_addr_1_reg_2743;
reg   [7:0] output_1_V_addr_1_reg_2748;
reg   [7:0] output_2_V_addr_1_reg_2753;
reg   [7:0] output_3_V_addr_1_reg_2758;
wire   [31:0] biased_V_fu_2093_p2;
reg   [31:0] biased_V_reg_2763;
reg    ap_sig_cseq_ST_st22_fsm_11;
reg    ap_sig_491;
wire   [30:0] tmp_31_fu_2098_p1;
reg   [30:0] tmp_31_reg_2768;
reg   [9:0] t_V_reg_446;
reg   [14:0] indvar_flatten1_phi_fu_461_p4;
reg   [6:0] t_V_1_phi_fu_472_p4;
reg   [9:0] indvar_flatten2_phi_fu_483_p4;
reg   [5:0] t_V_3_phi_fu_494_p4;
reg   [3:0] indvar_flatten_phi_fu_505_p4;
reg   [1:0] t_V_5_phi_fu_516_p4;
reg   [1:0] t_V_7_phi_fu_527_p4;
reg   [6:0] t_V_2_reg_534;
reg   [1:0] t_V_4_reg_546;
reg   [1:0] t_V_6_reg_557;
reg    ap_sig_cseq_ST_st23_fsm_12;
reg    ap_sig_538;
wire   [63:0] newIndex2_fu_612_p1;
wire   [63:0] OP2_V_cast_mid2_v_fu_1161_p1;
wire   [63:0] OP2_V_0_1_cast_mid2_v_fu_1179_p1;
wire   [63:0] tmp_9_fu_1390_p1;
wire   [63:0] tmp_17_1_fu_1401_p1;
wire   [63:0] OP2_V_0_2_cast_mid2_v_fu_1453_p1;
wire   [63:0] OP2_V_1_cast_mid2_v_fu_1457_p1;
wire   [63:0] tmp_17_0_1_fu_1471_p1;
wire   [63:0] tmp_17_0_2_fu_1486_p1;
wire   [63:0] OP2_V_1_1_cast_mid2_v_fu_1499_p1;
wire   [63:0] OP2_V_1_2_cast_mid2_v_fu_1503_p1;
wire   [63:0] tmp_17_1_1_fu_1534_p1;
wire   [63:0] tmp_17_1_2_fu_1543_p1;
wire   [63:0] OP2_V_2_cast_mid2_v_fu_1571_p1;
wire   [63:0] OP2_V_2_1_cast_mid2_v_fu_1575_p1;
wire   [63:0] tmp_17_2_fu_1599_p1;
wire   [63:0] tmp_17_2_1_fu_1603_p1;
wire   [63:0] OP2_V_2_2_cast_mid2_v_fu_1615_p1;
wire   [63:0] tmp_17_2_2_fu_1639_p1;
wire   [63:0] newIndex5_fu_1861_p1;
wire   [63:0] tmp_4_fu_1955_p1;
wire   [63:0] newIndex4_fu_2072_p1;
wire   [1:0] tmp_11_fu_598_p1;
wire   [31:0] p_Val2_5_fu_1935_p2;
wire   [31:0] p_Val2_2_cast_fu_2114_p1;
wire   [7:0] newIndex1_fu_602_p4;
wire   [5:0] tmp_1_fu_620_p1;
wire   [4:0] tmp_10_fu_636_p1;
wire   [10:0] p_s_fu_624_p3;
wire   [10:0] t_V_3_cast1_fu_632_p1;
wire   [10:0] tmp_6_fu_648_p2;
wire   [13:0] p_shl_fu_658_p3;
wire   [14:0] p_shl_cast_fu_666_p1;
wire   [14:0] tmp_6_cast1_fu_654_p1;
wire   [2:0] t_V_5_cast_fu_728_p1;
wire   [6:0] n_V1_fu_770_p2;
wire   [5:0] tmp_13_fu_776_p1;
wire   [10:0] p_mid1_fu_780_p3;
wire   [13:0] p_shl_mid_fu_812_p3;
wire   [14:0] p_shl_cast_mid_fu_820_p1;
wire   [14:0] tmp_6_cast1_mid_fu_808_p1;
wire   [6:0] t_V_5_cast1_fu_724_p1;
wire   [6:0] tmp17_fu_830_p2;
wire   [0:0] exitcond2_fu_850_p2;
wire   [0:0] not_exitcond_flatten_fu_844_p2;
wire   [0:0] exitcond_flatten1_fu_862_p2;
wire   [5:0] t_V_3_mid_fu_762_p3;
wire   [10:0] p_mid2_fu_788_p3;
wire   [10:0] t_V_3_cast1_mid1_fu_894_p1;
wire   [6:0] tmp4_cast_mid2177_v_fu_836_p3;
wire   [0:0] exitcond_flatten_not_fu_912_p2;
wire   [0:0] exitcond7_mid_fu_856_p2;
wire   [0:0] not_exitcond_flatten_mid_fu_918_p2;
wire   [0:0] tmp_17_fu_938_p2;
wire   [0:0] tmp_19_fu_944_p2;
wire   [5:0] t_V_7_cast_fu_958_p1;
wire   [3:0] indvar_flatten_op_fu_974_p2;
wire   [9:0] indvar_flatten38_op_fu_988_p2;
wire   [8:0] p_shl1_cast_mid2_v_fu_1002_p3;
wire   [14:0] w_index_V_0_1_mid_fu_1024_p2;
wire   [14:0] w_index_V_0_2_mid_fu_1035_p2;
wire   [14:0] w_index_V_1_mid_fu_1046_p2;
wire   [14:0] w_index_V_1_1_mid_fu_1057_p2;
wire   [14:0] w_index_V_1_2_mid_fu_1068_p2;
wire   [14:0] w_index_V_2_mid_fu_1079_p2;
wire   [14:0] w_index_V_2_1_mid_fu_1090_p2;
wire   [14:0] w_index_V_2_2_mid_fu_1101_p2;
wire   [4:0] tmp_18_fu_1112_p1;
wire   [6:0] p_shl2_mid1_fu_1115_p3;
wire   [6:0] p_shl2_cast_mid_fu_1013_p3;
wire   [6:0] p_shl2_cast_mid2_fu_1123_p3;
wire   [13:0] p_shl_mid1_fu_1137_p3;
wire   [14:0] p_shl_cast_mid1_fu_1144_p1;
wire   [14:0] tmp_6_cast1_mid1_fu_1134_p1;
wire   [14:0] tmp_7_mid1_fu_1148_p2;
wire   [14:0] OP2_V_cast_mid293_v_v_fu_1019_p3;
wire   [14:0] OP2_V_cast_mid2_v_v_fu_1154_p3;
wire   [14:0] w_index_V_0_1_mid1_fu_1166_p2;
wire   [14:0] OP2_V_0_1_cast_mid2101_v_v_fu_1029_p3;
wire   [14:0] OP2_V_0_1_cast_mid2_v_v_fu_1172_p3;
wire   [14:0] w_index_V_0_2_mid1_fu_1184_p2;
wire   [14:0] OP2_V_0_2_cast_mid2109_v_v_fu_1040_p3;
wire   [14:0] w_index_V_1_mid1_fu_1197_p2;
wire   [14:0] OP2_V_1_cast_mid2117_v_v_fu_1051_p3;
wire   [14:0] w_index_V_1_1_mid1_fu_1210_p2;
wire   [14:0] OP2_V_1_1_cast_mid2125_v_v_fu_1062_p3;
wire   [14:0] w_index_V_1_2_mid1_fu_1223_p2;
wire   [14:0] OP2_V_1_2_cast_mid2133_v_v_fu_1073_p3;
wire   [14:0] w_index_V_2_mid1_fu_1236_p2;
wire   [14:0] OP2_V_2_cast_mid2141_v_v_fu_1084_p3;
wire   [14:0] w_index_V_2_1_mid1_fu_1249_p2;
wire   [14:0] OP2_V_2_1_cast_mid2149_v_v_fu_1095_p3;
wire   [14:0] w_index_V_2_2_mid1_fu_1262_p2;
wire   [14:0] OP2_V_2_2_cast_mid2157_v_v_fu_1106_p3;
wire   [1:0] x_V_1_dup_fu_1287_p2;
wire   [1:0] x_V_1_mid1_fu_1310_p2;
wire   [1:0] tmp_15_1_cast_mid_fu_1275_p3;
wire   [1:0] tmp_15_1_cast_mid2_fu_1315_p3;
wire   [2:0] t_V_5_cast_mid1_fu_1306_p1;
wire   [2:0] tmp_15_2_mid1_fu_1326_p2;
wire   [2:0] tmp_15_2_cast_mid_fu_1281_p3;
wire   [6:0] t_V_5_cast1_mid1_fu_1292_p1;
wire   [6:0] tmp4_mid1_fu_1339_p2;
wire   [6:0] tmp4_cast_mid2_v_fu_1344_p3;
wire   [7:0] p_shl2_cast_mid2_cast_fu_1130_p1;
wire   [7:0] tmp3_cast_fu_1357_p1;
wire   [7:0] tmp1_fu_1360_p2;
wire   [9:0] tmp1_cast_fu_1366_p1;
wire   [9:0] p_shl4_fu_1370_p3;
wire   [9:0] i_index_V_fu_1384_p2;
wire   [9:0] i_index_V_1_fu_1395_p2;
wire   [3:0] p_shl3_fu_1406_p3;
wire   [4:0] p_shl3_cast_fu_1413_p1;
wire   [4:0] t_V_7_cast1_fu_1354_p1;
wire   [4:0] p_6_fu_1417_p2;
wire  signed [10:0] p_6_cast_fu_1423_p1;
wire   [10:0] p_shl1_cast_mid2_fu_1009_p1;
wire   [10:0] tmp4_cast_mid2_fu_1350_p1;
wire   [10:0] tmp5_fu_1427_p2;
wire   [10:0] o_index_V_fu_1433_p2;
wire   [9:0] i_index_V_0_1_fu_1466_p2;
wire   [9:0] i_index_V_0_2_fu_1481_p2;
wire   [9:0] i_index_V_1_1_fu_1530_p2;
wire   [9:0] i_index_V_1_2_fu_1539_p2;
wire   [9:0] tmp_15_2_cast_mid2_cast_fu_1507_p1;
wire   [60:0] grp_fu_1514_p2;
wire   [60:0] tmp_20_fu_1695_p3;
wire  signed [61:0] tmp_2115_0_1_cast_fu_1706_p1;
wire  signed [61:0] tmp_20_0_1_fu_1702_p1;
wire   [61:0] p_Val2_8_0_1_fu_1709_p2;
wire   [31:0] tmp_21_fu_1715_p4;
wire  signed [61:0] tmp_2115_0_2_cast_fu_1733_p1;
wire   [61:0] tmp_20_0_2_fu_1725_p3;
wire   [61:0] p_Val2_8_0_2_fu_1736_p2;
wire  signed [61:0] tmp_2115_1_cast_fu_1759_p1;
wire   [61:0] tmp_20_1_fu_1752_p3;
wire   [61:0] p_Val2_8_1_fu_1762_p2;
wire   [31:0] tmp_23_fu_1768_p4;
wire  signed [61:0] tmp_2115_1_1_cast_fu_1786_p1;
wire   [61:0] tmp_20_1_1_fu_1778_p3;
wire   [61:0] p_Val2_8_1_1_fu_1789_p2;
wire  signed [61:0] tmp_2115_1_2_cast_fu_1812_p1;
wire   [61:0] tmp_20_1_2_fu_1805_p3;
wire   [61:0] p_Val2_8_1_2_fu_1815_p2;
wire   [31:0] tmp_25_fu_1821_p4;
wire  signed [61:0] tmp_2115_2_cast_fu_1839_p1;
wire   [61:0] tmp_20_2_fu_1831_p3;
wire   [61:0] p_Val2_8_2_fu_1842_p2;
wire  signed [29:0] tmp_15_fu_1858_p1;
wire  signed [61:0] tmp_2115_2_1_cast_fu_1876_p1;
wire   [61:0] tmp_20_2_1_fu_1869_p3;
wire   [61:0] p_Val2_8_2_1_fu_1879_p2;
wire   [31:0] tmp_27_fu_1885_p4;
wire  signed [61:0] tmp_2115_2_2_cast_fu_1903_p1;
wire   [61:0] tmp_20_2_2_fu_1895_p3;
wire   [61:0] p_Val2_8_2_2_fu_1906_p2;
wire   [5:0] tmp_29_fu_1960_p1;
wire   [8:0] p_shl5_fu_1964_p3;
wire   [6:0] t_V_4_cast_fu_1980_p1;
wire   [6:0] tmp7_fu_1996_p2;
wire   [3:0] p_shl6_fu_2022_p3;
wire   [4:0] p_shl6_cast_fu_2030_p1;
wire   [4:0] t_V_6_cast_fu_2006_p1;
wire   [4:0] p_4_fu_2034_p2;
wire  signed [10:0] p_4_cast_fu_2040_p1;
wire   [10:0] tmp8_fu_2044_p2;
wire   [10:0] index_V_fu_2049_p2;
wire   [8:0] tmp_3_fu_2058_p4;
wire  signed [29:0] tmp_5_fu_2068_p1;
wire   [31:0] p_Val2_s_fu_2080_p6;
wire   [0:0] tmp_8_fu_2102_p2;
wire   [30:0] p_Val2_2_s_fu_2107_p3;
reg   [12:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'b1;
#0 ap_reg_ppiten_pp0_it0 = 1'b0;
#0 ap_reg_ppiten_pp0_it1 = 1'b0;
#0 ap_reg_ppiten_pp0_it2 = 1'b0;
end

dut_perform_conv_1_w_conv2 #(
    .DataWidth( 30 ),
    .AddressRange( 18432 ),
    .AddressWidth( 15 ))
w_conv2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_conv2_address0),
    .ce0(w_conv2_ce0),
    .q0(w_conv2_q0),
    .address1(w_conv2_address1),
    .ce1(w_conv2_ce1),
    .q1(w_conv2_q1)
);

dut_perform_conv_1_b_conv2 #(
    .DataWidth( 27 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
b_conv2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(b_conv2_address0),
    .ce0(b_conv2_ce0),
    .q0(b_conv2_q0)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_576),
    .din1(reg_568),
    .ce(1'b1),
    .dout(grp_fu_1514_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U43(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_581),
    .din1(w_conv2_q1),
    .ce(1'b1),
    .dout(grp_fu_1524_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U44(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_576),
    .din1(reg_572),
    .ce(1'b1),
    .dout(grp_fu_1583_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U45(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_581),
    .din1(reg_568),
    .ce(1'b1),
    .dout(grp_fu_1593_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U46(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_576),
    .din1(reg_568),
    .ce(1'b1),
    .dout(grp_fu_1623_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U47(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_581),
    .din1(reg_572),
    .ce(1'b1),
    .dout(grp_fu_1633_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U48(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_576),
    .din1(reg_568),
    .ce(1'b1),
    .dout(grp_fu_1655_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U49(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_581),
    .din1(reg_572),
    .ce(1'b1),
    .dout(grp_fu_1665_p2)
);

dut_mul_32s_30s_61_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 30 ),
    .dout_WIDTH( 61 ))
dut_mul_32s_30s_61_6_U50(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(reg_576),
    .din1(reg_568),
    .ce(1'b1),
    .dout(grp_fu_1679_p2)
);

dut_mux_4to1_sel2_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
dut_mux_4to1_sel2_32_1_U51(
    .din1(output_0_V_q0),
    .din2(output_1_V_q0),
    .din3(output_2_V_q0),
    .din4(output_3_V_q0),
    .din5(ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2),
    .dout(p_Val2_1_fu_1922_p6)
);

dut_mux_4to1_sel2_32_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
dut_mux_4to1_sel2_32_1_U52(
    .din1(output_0_V_q0),
    .din2(output_1_V_q0),
    .din3(output_2_V_q0),
    .din4(output_3_V_q0),
    .din5(tmp_30_reg_2738),
    .dout(p_Val2_s_fu_2080_p6)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= 1'b0;
    end else begin
        if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(1'b0 == exitcond_flatten2_fu_744_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b0;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
            ap_reg_ppiten_pp0_it0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= 1'b0;
    end else begin
        if (((exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b1;
        end else if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2)) | ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & ~(exitcond_flatten2_reg_2194 == 1'b0)))) begin
            ap_reg_ppiten_pp0_it1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end else if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
            ap_reg_ppiten_pp0_it2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        indvar_flatten1_reg_457 <= ap_const_lv15_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten1_reg_457 <= indvar_flatten_next2_reg_2198;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        indvar_flatten2_reg_479 <= ap_const_lv10_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten2_reg_479 <= indvar_flatten_next1_reg_2318;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        indvar_flatten_reg_501 <= ap_const_lv4_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten_reg_501 <= indvar_flatten_next_reg_2313;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)))) begin
        reg_576 <= input_V_q1;
    end else if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1)))) begin
        reg_576 <= input_V_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)))) begin
        reg_581 <= input_V_q0;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0))) begin
        reg_581 <= input_V_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        t_V_1_reg_468 <= ap_const_lv7_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_1_reg_468 <= p_shl1_cast_mid2_v_v_v_reg_2217;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st20_fsm_9) & ~(1'b0 == exitcond5_fu_1984_p2))) begin
        t_V_2_reg_534 <= n_V_reg_2697;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~(1'b0 == exitcond_flatten2_fu_744_p2))) begin
        t_V_2_reg_534 <= ap_const_lv7_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        t_V_3_reg_490 <= ap_const_lv6_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_3_reg_490 <= t_V_3_mid2_reg_2292;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st19_fsm_8)) begin
        t_V_4_reg_546 <= ap_const_lv2_0;
    end else if (((1'b1 == ap_sig_cseq_ST_st21_fsm_10) & ~(1'b0 == exitcond_fu_2010_p2))) begin
        t_V_4_reg_546 <= x_V_reg_2720;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        t_V_5_reg_512 <= ap_const_lv2_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_5_reg_512 <= t_V_5_cast2_mid2_reg_2368;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        t_V_6_reg_557 <= y_V_reg_2733;
    end else if (((1'b1 == ap_sig_cseq_ST_st20_fsm_9) & (1'b0 == exitcond5_fu_1984_p2))) begin
        t_V_6_reg_557 <= ap_const_lv2_0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & ~(1'b0 == exitcond1_fu_586_p2))) begin
        t_V_7_reg_523 <= ap_const_lv2_0;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_7_reg_523 <= y_V_1_reg_2308;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_586_p2))) begin
        t_V_reg_446 <= i_V_fu_592_p2;
    end else if (((1'b1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == 1'b0))) begin
        t_V_reg_446 <= ap_const_lv10_0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        OP2_V_0_2_cast_mid2_v_v_reg_2333 <= OP2_V_0_2_cast_mid2_v_v_fu_1190_p3;
        OP2_V_1_1_cast_mid2_v_v_reg_2343 <= OP2_V_1_1_cast_mid2_v_v_fu_1216_p3;
        OP2_V_1_2_cast_mid2_v_v_reg_2348 <= OP2_V_1_2_cast_mid2_v_v_fu_1229_p3;
        OP2_V_1_cast_mid2_v_v_reg_2338 <= OP2_V_1_cast_mid2_v_v_fu_1203_p3;
        OP2_V_2_1_cast_mid2_v_v_reg_2358 <= OP2_V_2_1_cast_mid2_v_v_fu_1255_p3;
        OP2_V_2_2_cast_mid2_v_v_reg_2363 <= OP2_V_2_2_cast_mid2_v_v_fu_1268_p3;
        OP2_V_2_cast_mid2_v_v_reg_2353 <= OP2_V_2_cast_mid2_v_v_fu_1242_p3;
        t_V_5_cast2_mid2_cast_reg_2373[1 : 0] <= t_V_5_cast2_mid2_cast_fu_1302_p1[1 : 0];
        tmp10_reg_2390 <= tmp10_fu_1378_p2;
        tmp_12_reg_2412 <= {{o_index_V_fu_1433_p2[ap_const_lv32_A : ap_const_lv32_2]}};
        tmp_15_1_cast_mid2_cast_reg_2379[1 : 0] <= tmp_15_1_cast_mid2_cast_fu_1322_p1[1 : 0];
        tmp_15_2_cast_mid2_reg_2385 <= tmp_15_2_cast_mid2_fu_1332_p3;
        tmp_28_reg_2407 <= tmp_28_fu_1439_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)) begin
        ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1 <= exitcond_flatten2_reg_2194;
        ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter2 <= ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1;
        exitcond_flatten2_reg_2194 <= exitcond_flatten2_fu_744_p2;
        p_shl2_reg_2134[6 : 2] <= p_shl2_fu_640_p3[6 : 2];
        tmp_15_2_reg_2189 <= tmp_15_2_fu_738_p2;
        tmp_7_reg_2139 <= tmp_7_fu_670_p2;
        w_index_V_0_1_reg_2144 <= w_index_V_0_1_fu_676_p2;
        w_index_V_0_2_reg_2149 <= w_index_V_0_2_fu_682_p2;
        w_index_V_1_1_reg_2159 <= w_index_V_1_1_fu_694_p2;
        w_index_V_1_2_reg_2164 <= w_index_V_1_2_fu_700_p2;
        w_index_V_1_reg_2154 <= w_index_V_1_fu_688_p2;
        w_index_V_2_1_reg_2174 <= w_index_V_2_1_fu_712_p2;
        w_index_V_2_2_reg_2179 <= w_index_V_2_2_fu_718_p2;
        w_index_V_2_reg_2169 <= w_index_V_2_fu_706_p2;
        x_V_1_reg_2184 <= x_V_1_fu_732_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
        ap_reg_ppstg_tmp_12_reg_2412_pp0_iter1 <= tmp_12_reg_2412;
        ap_reg_ppstg_tmp_12_reg_2412_pp0_iter2 <= ap_reg_ppstg_tmp_12_reg_2412_pp0_iter1;
        ap_reg_ppstg_tmp_28_reg_2407_pp0_iter1 <= tmp_28_reg_2407;
        ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2 <= ap_reg_ppstg_tmp_28_reg_2407_pp0_iter1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st22_fsm_11)) begin
        biased_V_reg_2763 <= biased_V_fu_2093_p2;
        tmp_31_reg_2768 <= tmp_31_fu_2098_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == exitcond_flatten2_fu_744_p2))) begin
        exitcond7_mid1_reg_2284 <= exitcond7_mid1_fu_924_p2;
        exitcond_flatten_mid_reg_2241 <= exitcond_flatten_mid_fu_868_p2;
        exitcond_flatten_reg_2203 <= exitcond_flatten_fu_756_p2;
        m_V_reg_2255 <= m_V_fu_874_p2;
        t_V_5_mid_reg_2266 <= t_V_5_mid_fu_886_p3;
        t_V_7_mid2_reg_2297 <= t_V_7_mid2_fu_950_p3;
        tmp3_reg_2303 <= tmp3_fu_962_p2;
        tmp4_cast_mid235_v_reg_2279 <= tmp4_cast_mid235_v_fu_904_p3;
        tmp_14_reg_2260 <= tmp_14_fu_880_p2;
        tmp_16_reg_2223 <= tmp_16_fu_804_p1;
        tmp_6_mid1_reg_2273 <= tmp_6_mid1_fu_898_p2;
        tmp_7_mid_reg_2228[14 : 5] <= tmp_7_mid_fu_824_p2[14 : 5];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        i_index_V_2_1_reg_2494 <= i_index_V_2_1_fu_1553_p2;
        i_index_V_2_2_reg_2499 <= i_index_V_2_2_fu_1558_p2;
        i_index_V_2_reg_2489 <= i_index_V_2_fu_1548_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == exitcond_flatten2_fu_744_p2))) begin
        indvar_flatten_next1_reg_2318 <= indvar_flatten_next1_fu_994_p3;
        indvar_flatten_next_reg_2313 <= indvar_flatten_next_fu_980_p3;
        p_shl1_cast_mid2_v_v_v_reg_2217 <= p_shl1_cast_mid2_v_v_v_fu_796_p3;
        t_V_3_mid2_reg_2292 <= t_V_3_mid2_fu_930_p3;
        y_V_1_reg_2308 <= y_V_1_fu_968_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten_next2_reg_2198 <= indvar_flatten_next2_fu_750_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st18_fsm_7)) begin
        n_V_reg_2697 <= n_V_fu_1949_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st21_fsm_10) & (1'b0 == exitcond_fu_2010_p2))) begin
        output_0_V_addr_1_reg_2743 <= newIndex4_fu_2072_p1;
        output_1_V_addr_1_reg_2748 <= newIndex4_fu_2072_p1;
        output_2_V_addr_1_reg_2753 <= newIndex4_fu_2072_p1;
        output_3_V_addr_1_reg_2758 <= newIndex4_fu_2072_p1;
        tmp_30_reg_2738 <= tmp_30_fu_2054_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter2))) begin
        output_0_V_addr_2_reg_2664 <= newIndex5_fu_1861_p1;
        output_1_V_addr_2_reg_2669 <= newIndex5_fu_1861_p1;
        output_2_V_addr_2_reg_2674 <= newIndex5_fu_1861_p1;
        output_3_V_addr_2_reg_2679 <= newIndex5_fu_1861_p1;
        p_Val2_7_2_2_reg_2659 <= grp_fu_1679_p2;
        tmp_26_reg_2654 <= {{p_Val2_8_2_fu_1842_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st19_fsm_8)) begin
        p_Val2_1_cast_reg_2712[26 : 0] <= p_Val2_1_cast_fu_1976_p1[26 : 0];
        p_shl5_cast_reg_2707[8 : 3] <= p_shl5_cast_fu_1972_p1[8 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter2))) begin
        p_Val2_1_reg_2689 <= p_Val2_1_fu_1922_p6;
        sum_V_2_2_reg_2684 <= {{p_Val2_8_2_2_fu_1906_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1))) begin
        p_Val2_7_0_1_reg_2614 <= grp_fu_1583_p2;
        p_Val2_7_0_2_reg_2619 <= grp_fu_1593_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1))) begin
        p_Val2_7_1_1_reg_2629 <= grp_fu_1623_p2;
        p_Val2_7_1_2_reg_2634 <= grp_fu_1633_p2;
        tmp_22_reg_2624 <= {{p_Val2_8_0_2_fu_1736_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1))) begin
        p_Val2_7_1_reg_2609 <= grp_fu_1524_p2;
        tmp_s_reg_2604 <= {{grp_fu_1514_p2[ap_const_lv32_3C : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter2))) begin
        p_Val2_7_2_1_reg_2649 <= grp_fu_1665_p2;
        p_Val2_7_2_reg_2644 <= grp_fu_1655_p2;
        tmp_24_reg_2639 <= {{p_Val2_8_1_1_fu_1789_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3) & (1'b0 == ap_reg_ppstg_exitcond_flatten2_reg_2194_pp0_iter1)))) begin
        reg_568 <= w_conv2_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)))) begin
        reg_572 <= w_conv2_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it0) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        t_V_5_cast2_mid2_reg_2368 <= t_V_5_cast2_mid2_fu_1296_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (exitcond_flatten2_reg_2194 == 1'b0))) begin
        tmp1_0_1_reg_2427 <= tmp1_0_1_fu_1461_p2;
        tmp1_0_2_reg_2438 <= tmp1_0_2_fu_1476_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_sig_cseq_ST_st20_fsm_9) & (1'b0 == exitcond5_fu_1984_p2))) begin
        tmp7_cast_reg_2725[6 : 0] <= tmp7_cast_fu_2002_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st20_fsm_9)) begin
        x_V_reg_2720 <= x_V_fu_1990_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_sig_cseq_ST_st21_fsm_10)) begin
        y_V_reg_2733 <= y_V_fu_2016_p2;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0)) | ((1'b1 == ap_sig_cseq_ST_st18_fsm_7) & ~(1'b0 == exitcond3_fu_1943_p2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_start) & (1'b1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st18_fsm_7) & ~(1'b0 == exitcond3_fu_1943_p2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_152) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_162) begin
        ap_sig_cseq_ST_pp0_stg1_fsm_3 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg1_fsm_3 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_114) begin
        ap_sig_cseq_ST_pp0_stg2_fsm_4 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg2_fsm_4 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_132) begin
        ap_sig_cseq_ST_pp0_stg3_fsm_5 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg3_fsm_5 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_142) begin
        ap_sig_cseq_ST_pp0_stg4_fsm_6 = 1'b1;
    end else begin
        ap_sig_cseq_ST_pp0_stg4_fsm_6 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_430) begin
        ap_sig_cseq_ST_st18_fsm_7 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st18_fsm_7 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_444) begin
        ap_sig_cseq_ST_st19_fsm_8 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st19_fsm_8 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_30) begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_455) begin
        ap_sig_cseq_ST_st20_fsm_9 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st20_fsm_9 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_469) begin
        ap_sig_cseq_ST_st21_fsm_10 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st21_fsm_10 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_491) begin
        ap_sig_cseq_ST_st22_fsm_11 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st22_fsm_11 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_538) begin
        ap_sig_cseq_ST_st23_fsm_12 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st23_fsm_12 = 1'b0;
    end
end

always @ (*) begin
    if (ap_sig_184) begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st18_fsm_7)) begin
        b_conv2_ce0 = 1'b1;
    end else begin
        b_conv2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten1_phi_fu_461_p4 = indvar_flatten_next2_reg_2198;
    end else begin
        indvar_flatten1_phi_fu_461_p4 = indvar_flatten1_reg_457;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten2_phi_fu_483_p4 = indvar_flatten_next1_reg_2318;
    end else begin
        indvar_flatten2_phi_fu_483_p4 = indvar_flatten2_reg_479;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        indvar_flatten_phi_fu_505_p4 = indvar_flatten_next_reg_2313;
    end else begin
        indvar_flatten_phi_fu_505_p4 = indvar_flatten_reg_501;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        input_V_address0 = tmp_17_2_2_fu_1639_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        input_V_address0 = tmp_17_2_1_fu_1603_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        input_V_address0 = tmp_17_1_2_fu_1543_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        input_V_address0 = tmp_17_0_2_fu_1486_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        input_V_address0 = tmp_9_fu_1390_p1;
    end else begin
        input_V_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            input_V_address1 = tmp_17_2_fu_1599_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            input_V_address1 = tmp_17_1_1_fu_1534_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            input_V_address1 = tmp_17_0_1_fu_1471_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            input_V_address1 = tmp_17_1_fu_1401_p1;
        end else begin
            input_V_address1 = 'bx;
        end
    end else begin
        input_V_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)))) begin
        input_V_ce0 = 1'b1;
    end else begin
        input_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)))) begin
        input_V_ce1 = 1'b1;
    end else begin
        input_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_0_V_address0 = output_0_V_addr_1_reg_2743;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_0_V_address0 = output_0_V_addr_2_reg_2664;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_0_V_address0 = newIndex2_fu_612_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st21_fsm_10)) begin
        output_0_V_address0 = newIndex4_fu_2072_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2))) begin
        output_0_V_address0 = newIndex5_fu_1861_p1;
    end else begin
        output_0_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st21_fsm_10) | (1'b1 == ap_sig_cseq_ST_st23_fsm_12) | ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        output_0_V_ce0 = 1'b1;
    end else begin
        output_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_0_V_d0 = p_Val2_2_cast_fu_2114_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_0_V_d0 = p_Val2_5_fu_1935_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_0_V_d0 = ap_const_lv32_0;
    end else begin
        output_0_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_586_p2) & (ap_const_lv2_0 == tmp_11_fu_598_p1)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2 == ap_const_lv2_0)) | ((1'b1 == ap_sig_cseq_ST_st23_fsm_12) & (tmp_30_reg_2738 == ap_const_lv2_0)))) begin
        output_0_V_we0 = 1'b1;
    end else begin
        output_0_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_1_V_address0 = output_1_V_addr_1_reg_2748;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_1_V_address0 = output_1_V_addr_2_reg_2669;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_1_V_address0 = newIndex2_fu_612_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st21_fsm_10)) begin
        output_1_V_address0 = newIndex4_fu_2072_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2))) begin
        output_1_V_address0 = newIndex5_fu_1861_p1;
    end else begin
        output_1_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st21_fsm_10) | (1'b1 == ap_sig_cseq_ST_st23_fsm_12) | ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        output_1_V_ce0 = 1'b1;
    end else begin
        output_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_1_V_d0 = p_Val2_2_cast_fu_2114_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_1_V_d0 = p_Val2_5_fu_1935_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_1_V_d0 = ap_const_lv32_0;
    end else begin
        output_1_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_586_p2) & (tmp_11_fu_598_p1 == ap_const_lv2_1)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2 == ap_const_lv2_1)) | ((1'b1 == ap_sig_cseq_ST_st23_fsm_12) & (tmp_30_reg_2738 == ap_const_lv2_1)))) begin
        output_1_V_we0 = 1'b1;
    end else begin
        output_1_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_2_V_address0 = output_2_V_addr_1_reg_2753;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_2_V_address0 = output_2_V_addr_2_reg_2674;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_2_V_address0 = newIndex2_fu_612_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st21_fsm_10)) begin
        output_2_V_address0 = newIndex4_fu_2072_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2))) begin
        output_2_V_address0 = newIndex5_fu_1861_p1;
    end else begin
        output_2_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st21_fsm_10) | (1'b1 == ap_sig_cseq_ST_st23_fsm_12) | ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        output_2_V_ce0 = 1'b1;
    end else begin
        output_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_2_V_d0 = p_Val2_2_cast_fu_2114_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_2_V_d0 = p_Val2_5_fu_1935_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_2_V_d0 = ap_const_lv32_0;
    end else begin
        output_2_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_586_p2) & (tmp_11_fu_598_p1 == ap_const_lv2_2)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2 == ap_const_lv2_2)) | ((1'b1 == ap_sig_cseq_ST_st23_fsm_12) & (tmp_30_reg_2738 == ap_const_lv2_2)))) begin
        output_2_V_we0 = 1'b1;
    end else begin
        output_2_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_3_V_address0 = output_3_V_addr_1_reg_2758;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_3_V_address0 = output_3_V_addr_2_reg_2679;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_3_V_address0 = newIndex2_fu_612_p1;
    end else if ((1'b1 == ap_sig_cseq_ST_st21_fsm_10)) begin
        output_3_V_address0 = newIndex4_fu_2072_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2))) begin
        output_3_V_address0 = newIndex5_fu_1861_p1;
    end else begin
        output_3_V_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_sig_cseq_ST_st2_fsm_1) | (1'b1 == ap_sig_cseq_ST_st21_fsm_10) | (1'b1 == ap_sig_cseq_ST_st23_fsm_12) | ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it2)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)))) begin
        output_3_V_ce0 = 1'b1;
    end else begin
        output_3_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_sig_cseq_ST_st23_fsm_12)) begin
        output_3_V_d0 = p_Val2_2_cast_fu_2114_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        output_3_V_d0 = p_Val2_5_fu_1935_p2;
    end else if ((1'b1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        output_3_V_d0 = ap_const_lv32_0;
    end else begin
        output_3_V_d0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_st2_fsm_1) & (1'b0 == exitcond1_fu_586_p2) & (tmp_11_fu_598_p1 == ap_const_lv2_3)) | ((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & (ap_reg_ppstg_tmp_28_reg_2407_pp0_iter2 == ap_const_lv2_3)) | ((1'b1 == ap_sig_cseq_ST_st23_fsm_12) & (tmp_30_reg_2738 == ap_const_lv2_3)))) begin
        output_3_V_we0 = 1'b1;
    end else begin
        output_3_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_1_phi_fu_472_p4 = p_shl1_cast_mid2_v_v_v_reg_2217;
    end else begin
        t_V_1_phi_fu_472_p4 = t_V_1_reg_468;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_3_phi_fu_494_p4 = t_V_3_mid2_reg_2292;
    end else begin
        t_V_3_phi_fu_494_p4 = t_V_3_reg_490;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_5_phi_fu_516_p4 = t_V_5_cast2_mid2_reg_2368;
    end else begin
        t_V_5_phi_fu_516_p4 = t_V_5_reg_512;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (exitcond_flatten2_reg_2194 == 1'b0) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        t_V_7_phi_fu_527_p4 = y_V_1_reg_2308;
    end else begin
        t_V_7_phi_fu_527_p4 = t_V_7_reg_523;
    end
end

always @ (*) begin
    if (((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2))) begin
        w_conv2_address0 = OP2_V_2_2_cast_mid2_v_fu_1615_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6))) begin
        w_conv2_address0 = OP2_V_2_cast_mid2_v_fu_1571_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5))) begin
        w_conv2_address0 = OP2_V_1_1_cast_mid2_v_fu_1499_p1;
    end else if (((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0))) begin
        w_conv2_address0 = OP2_V_0_2_cast_mid2_v_fu_1453_p1;
    end else if (((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3))) begin
        w_conv2_address0 = OP2_V_cast_mid2_v_fu_1161_p1;
    end else begin
        w_conv2_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_reg_ppiten_pp0_it0)) begin
        if ((1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) begin
            w_conv2_address1 = OP2_V_2_1_cast_mid2_v_fu_1575_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) begin
            w_conv2_address1 = OP2_V_1_2_cast_mid2_v_fu_1503_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4)) begin
            w_conv2_address1 = OP2_V_1_cast_mid2_v_fu_1457_p1;
        end else if ((1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)) begin
            w_conv2_address1 = OP2_V_0_1_cast_mid2_v_fu_1179_p1;
        end else begin
            w_conv2_address1 = 'bx;
        end
    end else begin
        w_conv2_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it1) & (1'b1 == ap_sig_cseq_ST_pp0_stg0_fsm_2)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)))) begin
        w_conv2_ce0 = 1'b1;
    end else begin
        w_conv2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_sig_cseq_ST_pp0_stg2_fsm_4) & (1'b1 == ap_reg_ppiten_pp0_it0)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg3_fsm_5)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6)) | ((1'b1 == ap_reg_ppiten_pp0_it0) & (1'b1 == ap_sig_cseq_ST_pp0_stg1_fsm_3)))) begin
        w_conv2_ce1 = 1'b1;
    end else begin
        w_conv2_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : begin
            if (~(ap_start == 1'b0)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : begin
            if ((1'b0 == exitcond1_fu_586_p2)) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it0) & ~(1'b0 == exitcond_flatten2_fu_744_p2) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp0_stg1_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_7;
            end
        end
        ap_ST_pp0_stg1_fsm_3 : begin
            ap_NS_fsm = ap_ST_pp0_stg2_fsm_4;
        end
        ap_ST_pp0_stg2_fsm_4 : begin
            ap_NS_fsm = ap_ST_pp0_stg3_fsm_5;
        end
        ap_ST_pp0_stg3_fsm_5 : begin
            ap_NS_fsm = ap_ST_pp0_stg4_fsm_6;
        end
        ap_ST_pp0_stg4_fsm_6 : begin
            if (~((1'b1 == ap_reg_ppiten_pp0_it2) & (1'b1 == ap_sig_cseq_ST_pp0_stg4_fsm_6) & ~(1'b1 == ap_reg_ppiten_pp0_it1))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_7;
            end
        end
        ap_ST_st18_fsm_7 : begin
            if (~(1'b0 == exitcond3_fu_1943_p2)) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st19_fsm_8;
            end
        end
        ap_ST_st19_fsm_8 : begin
            ap_NS_fsm = ap_ST_st20_fsm_9;
        end
        ap_ST_st20_fsm_9 : begin
            if ((1'b0 == exitcond5_fu_1984_p2)) begin
                ap_NS_fsm = ap_ST_st21_fsm_10;
            end else begin
                ap_NS_fsm = ap_ST_st18_fsm_7;
            end
        end
        ap_ST_st21_fsm_10 : begin
            if (~(1'b0 == exitcond_fu_2010_p2)) begin
                ap_NS_fsm = ap_ST_st20_fsm_9;
            end else begin
                ap_NS_fsm = ap_ST_st22_fsm_11;
            end
        end
        ap_ST_st22_fsm_11 : begin
            ap_NS_fsm = ap_ST_st23_fsm_12;
        end
        ap_ST_st23_fsm_12 : begin
            ap_NS_fsm = ap_ST_st21_fsm_10;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign OP2_V_0_1_cast_mid2101_v_v_fu_1029_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_0_1_mid_fu_1024_p2 : w_index_V_0_1_reg_2144);

assign OP2_V_0_1_cast_mid2_v_fu_1179_p1 = OP2_V_0_1_cast_mid2_v_v_fu_1172_p3;

assign OP2_V_0_1_cast_mid2_v_v_fu_1172_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_0_1_mid1_fu_1166_p2 : OP2_V_0_1_cast_mid2101_v_v_fu_1029_p3);

assign OP2_V_0_2_cast_mid2109_v_v_fu_1040_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_0_2_mid_fu_1035_p2 : w_index_V_0_2_reg_2149);

assign OP2_V_0_2_cast_mid2_v_fu_1453_p1 = OP2_V_0_2_cast_mid2_v_v_reg_2333;

assign OP2_V_0_2_cast_mid2_v_v_fu_1190_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_0_2_mid1_fu_1184_p2 : OP2_V_0_2_cast_mid2109_v_v_fu_1040_p3);

assign OP2_V_1_1_cast_mid2125_v_v_fu_1062_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_1_1_mid_fu_1057_p2 : w_index_V_1_1_reg_2159);

assign OP2_V_1_1_cast_mid2_v_fu_1499_p1 = OP2_V_1_1_cast_mid2_v_v_reg_2343;

assign OP2_V_1_1_cast_mid2_v_v_fu_1216_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_1_1_mid1_fu_1210_p2 : OP2_V_1_1_cast_mid2125_v_v_fu_1062_p3);

assign OP2_V_1_2_cast_mid2133_v_v_fu_1073_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_1_2_mid_fu_1068_p2 : w_index_V_1_2_reg_2164);

assign OP2_V_1_2_cast_mid2_v_fu_1503_p1 = OP2_V_1_2_cast_mid2_v_v_reg_2348;

assign OP2_V_1_2_cast_mid2_v_v_fu_1229_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_1_2_mid1_fu_1223_p2 : OP2_V_1_2_cast_mid2133_v_v_fu_1073_p3);

assign OP2_V_1_cast_mid2117_v_v_fu_1051_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_1_mid_fu_1046_p2 : w_index_V_1_reg_2154);

assign OP2_V_1_cast_mid2_v_fu_1457_p1 = OP2_V_1_cast_mid2_v_v_reg_2338;

assign OP2_V_1_cast_mid2_v_v_fu_1203_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_1_mid1_fu_1197_p2 : OP2_V_1_cast_mid2117_v_v_fu_1051_p3);

assign OP2_V_2_1_cast_mid2149_v_v_fu_1095_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_2_1_mid_fu_1090_p2 : w_index_V_2_1_reg_2174);

assign OP2_V_2_1_cast_mid2_v_fu_1575_p1 = OP2_V_2_1_cast_mid2_v_v_reg_2358;

assign OP2_V_2_1_cast_mid2_v_v_fu_1255_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_2_1_mid1_fu_1249_p2 : OP2_V_2_1_cast_mid2149_v_v_fu_1095_p3);

assign OP2_V_2_2_cast_mid2157_v_v_fu_1106_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_2_2_mid_fu_1101_p2 : w_index_V_2_2_reg_2179);

assign OP2_V_2_2_cast_mid2_v_fu_1615_p1 = OP2_V_2_2_cast_mid2_v_v_reg_2363;

assign OP2_V_2_2_cast_mid2_v_v_fu_1268_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_2_2_mid1_fu_1262_p2 : OP2_V_2_2_cast_mid2157_v_v_fu_1106_p3);

assign OP2_V_2_cast_mid2141_v_v_fu_1084_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? w_index_V_2_mid_fu_1079_p2 : w_index_V_2_reg_2169);

assign OP2_V_2_cast_mid2_v_fu_1571_p1 = OP2_V_2_cast_mid2_v_v_reg_2353;

assign OP2_V_2_cast_mid2_v_v_fu_1242_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? w_index_V_2_mid1_fu_1236_p2 : OP2_V_2_cast_mid2141_v_v_fu_1084_p3);

assign OP2_V_cast_mid293_v_v_fu_1019_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? tmp_7_mid_reg_2228 : tmp_7_reg_2139);

assign OP2_V_cast_mid2_v_fu_1161_p1 = OP2_V_cast_mid2_v_v_fu_1154_p3;

assign OP2_V_cast_mid2_v_v_fu_1154_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? tmp_7_mid1_fu_1148_p2 : OP2_V_cast_mid293_v_v_fu_1019_p3);

always @ (*) begin
    ap_sig_114 = (1'b1 == ap_CS_fsm[ap_const_lv32_4]);
end

always @ (*) begin
    ap_sig_132 = (1'b1 == ap_CS_fsm[ap_const_lv32_5]);
end

always @ (*) begin
    ap_sig_142 = (1'b1 == ap_CS_fsm[ap_const_lv32_6]);
end

always @ (*) begin
    ap_sig_152 = (1'b1 == ap_CS_fsm[ap_const_lv32_2]);
end

always @ (*) begin
    ap_sig_162 = (1'b1 == ap_CS_fsm[ap_const_lv32_3]);
end

always @ (*) begin
    ap_sig_184 = (1'b1 == ap_CS_fsm[ap_const_lv32_1]);
end

always @ (*) begin
    ap_sig_30 = (ap_CS_fsm[ap_const_lv32_0] == 1'b1);
end

always @ (*) begin
    ap_sig_430 = (1'b1 == ap_CS_fsm[ap_const_lv32_7]);
end

always @ (*) begin
    ap_sig_444 = (1'b1 == ap_CS_fsm[ap_const_lv32_8]);
end

always @ (*) begin
    ap_sig_455 = (1'b1 == ap_CS_fsm[ap_const_lv32_9]);
end

always @ (*) begin
    ap_sig_469 = (1'b1 == ap_CS_fsm[ap_const_lv32_A]);
end

always @ (*) begin
    ap_sig_491 = (1'b1 == ap_CS_fsm[ap_const_lv32_B]);
end

always @ (*) begin
    ap_sig_538 = (1'b1 == ap_CS_fsm[ap_const_lv32_C]);
end

assign b_conv2_address0 = tmp_4_fu_1955_p1;

assign biased_V_fu_2093_p2 = (p_Val2_1_cast_reg_2712 + p_Val2_s_fu_2080_p6);

assign exitcond1_fu_586_p2 = ((t_V_reg_446 == ap_const_lv10_320) ? 1'b1 : 1'b0);

assign exitcond2_fu_850_p2 = ((t_V_7_phi_fu_527_p4 == ap_const_lv2_3) ? 1'b1 : 1'b0);

assign exitcond3_fu_1943_p2 = ((t_V_2_reg_534 == ap_const_lv7_40) ? 1'b1 : 1'b0);

assign exitcond5_fu_1984_p2 = ((t_V_4_reg_546 == ap_const_lv2_3) ? 1'b1 : 1'b0);

assign exitcond7_mid1_fu_924_p2 = (exitcond7_mid_fu_856_p2 & not_exitcond_flatten_mid_fu_918_p2);

assign exitcond7_mid_fu_856_p2 = (exitcond2_fu_850_p2 & not_exitcond_flatten_fu_844_p2);

assign exitcond_flatten1_fu_862_p2 = ((indvar_flatten_phi_fu_505_p4 == ap_const_lv4_9) ? 1'b1 : 1'b0);

assign exitcond_flatten2_fu_744_p2 = ((indvar_flatten1_phi_fu_461_p4 == ap_const_lv15_4800) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_756_p2 = ((indvar_flatten2_phi_fu_483_p4 == ap_const_lv10_120) ? 1'b1 : 1'b0);

assign exitcond_flatten_mid_fu_868_p2 = (exitcond_flatten1_fu_862_p2 & not_exitcond_flatten_fu_844_p2);

assign exitcond_flatten_not_fu_912_p2 = (exitcond_flatten1_fu_862_p2 ^ 1'b1);

assign exitcond_fu_2010_p2 = ((t_V_6_reg_557 == ap_const_lv2_3) ? 1'b1 : 1'b0);

assign i_V_fu_592_p2 = (t_V_reg_446 + ap_const_lv10_1);

assign i_index_V_0_1_fu_1466_p2 = (tmp1_0_1_fu_1461_p2 + t_V_5_cast2_mid2_cast_reg_2373);

assign i_index_V_0_2_fu_1481_p2 = (tmp1_0_2_fu_1476_p2 + t_V_5_cast2_mid2_cast_reg_2373);

assign i_index_V_1_1_fu_1530_p2 = (tmp1_0_1_reg_2427 + tmp_15_1_cast_mid2_cast_reg_2379);

assign i_index_V_1_2_fu_1539_p2 = (tmp1_0_2_reg_2438 + tmp_15_1_cast_mid2_cast_reg_2379);

assign i_index_V_1_fu_1395_p2 = (tmp10_fu_1378_p2 + tmp_15_1_cast_mid2_cast_fu_1322_p1);

assign i_index_V_2_1_fu_1553_p2 = (tmp1_0_1_reg_2427 + tmp_15_2_cast_mid2_cast_fu_1507_p1);

assign i_index_V_2_2_fu_1558_p2 = (tmp1_0_2_reg_2438 + tmp_15_2_cast_mid2_cast_fu_1507_p1);

assign i_index_V_2_fu_1548_p2 = (tmp10_reg_2390 + tmp_15_2_cast_mid2_cast_fu_1507_p1);

assign i_index_V_fu_1384_p2 = (tmp10_fu_1378_p2 + t_V_5_cast2_mid2_cast_fu_1302_p1);

assign index_V_fu_2049_p2 = (tmp8_fu_2044_p2 + tmp7_cast_reg_2725);

assign indvar_flatten38_op_fu_988_p2 = (indvar_flatten2_phi_fu_483_p4 + ap_const_lv10_1);

assign indvar_flatten_next1_fu_994_p3 = ((exitcond_flatten_fu_756_p2[0:0] === 1'b1) ? ap_const_lv10_1 : indvar_flatten38_op_fu_988_p2);

assign indvar_flatten_next2_fu_750_p2 = (ap_const_lv15_1 + indvar_flatten1_phi_fu_461_p4);

assign indvar_flatten_next_fu_980_p3 = ((tmp_14_fu_880_p2[0:0] === 1'b1) ? ap_const_lv4_1 : indvar_flatten_op_fu_974_p2);

assign indvar_flatten_op_fu_974_p2 = (indvar_flatten_phi_fu_505_p4 + ap_const_lv4_1);

assign m_V_fu_874_p2 = (ap_const_lv6_1 + t_V_3_mid_fu_762_p3);

assign n_V1_fu_770_p2 = (ap_const_lv7_1 + t_V_1_phi_fu_472_p4);

assign n_V_fu_1949_p2 = (t_V_2_reg_534 + ap_const_lv7_1);

assign newIndex1_fu_602_p4 = {{t_V_reg_446[ap_const_lv32_9 : ap_const_lv32_2]}};

assign newIndex2_fu_612_p1 = newIndex1_fu_602_p4;

assign newIndex4_fu_2072_p1 = $unsigned(tmp_5_fu_2068_p1);

assign newIndex5_fu_1861_p1 = $unsigned(tmp_15_fu_1858_p1);

assign not_exitcond_flatten_fu_844_p2 = (exitcond_flatten_fu_756_p2 ^ 1'b1);

assign not_exitcond_flatten_mid_fu_918_p2 = (exitcond_flatten_fu_756_p2 | exitcond_flatten_not_fu_912_p2);

assign o_index_V_fu_1433_p2 = (tmp4_cast_mid2_fu_1350_p1 + tmp5_fu_1427_p2);

assign p_4_cast_fu_2040_p1 = $signed(p_4_fu_2034_p2);

assign p_4_fu_2034_p2 = (p_shl6_cast_fu_2030_p1 - t_V_6_cast_fu_2006_p1);

assign p_6_cast_fu_1423_p1 = $signed(p_6_fu_1417_p2);

assign p_6_fu_1417_p2 = (p_shl3_cast_fu_1413_p1 - t_V_7_cast1_fu_1354_p1);

assign p_Val2_1_cast_fu_1976_p1 = b_conv2_q0;

assign p_Val2_2_cast_fu_2114_p1 = p_Val2_2_s_fu_2107_p3;

assign p_Val2_2_s_fu_2107_p3 = ((tmp_8_fu_2102_p2[0:0] === 1'b1) ? tmp_31_reg_2768 : ap_const_lv31_0);

assign p_Val2_5_fu_1935_p2 = (sum_V_2_2_reg_2684 + p_Val2_1_reg_2689);

assign p_Val2_8_0_1_fu_1709_p2 = ($signed(tmp_2115_0_1_cast_fu_1706_p1) + $signed(tmp_20_0_1_fu_1702_p1));

assign p_Val2_8_0_2_fu_1736_p2 = ($signed(tmp_2115_0_2_cast_fu_1733_p1) + $signed(tmp_20_0_2_fu_1725_p3));

assign p_Val2_8_1_1_fu_1789_p2 = ($signed(tmp_2115_1_1_cast_fu_1786_p1) + $signed(tmp_20_1_1_fu_1778_p3));

assign p_Val2_8_1_2_fu_1815_p2 = ($signed(tmp_2115_1_2_cast_fu_1812_p1) + $signed(tmp_20_1_2_fu_1805_p3));

assign p_Val2_8_1_fu_1762_p2 = ($signed(tmp_2115_1_cast_fu_1759_p1) + $signed(tmp_20_1_fu_1752_p3));

assign p_Val2_8_2_1_fu_1879_p2 = ($signed(tmp_2115_2_1_cast_fu_1876_p1) + $signed(tmp_20_2_1_fu_1869_p3));

assign p_Val2_8_2_2_fu_1906_p2 = ($signed(tmp_2115_2_2_cast_fu_1903_p1) + $signed(tmp_20_2_2_fu_1895_p3));

assign p_Val2_8_2_fu_1842_p2 = ($signed(tmp_2115_2_cast_fu_1839_p1) + $signed(tmp_20_2_fu_1831_p3));

assign p_mid1_fu_780_p3 = {{tmp_13_fu_776_p1}, {ap_const_lv5_0}};

assign p_mid2_fu_788_p3 = ((exitcond_flatten_fu_756_p2[0:0] === 1'b1) ? p_mid1_fu_780_p3 : p_s_fu_624_p3);

assign p_s_fu_624_p3 = {{tmp_1_fu_620_p1}, {ap_const_lv5_0}};

assign p_shl1_cast_mid2_fu_1009_p1 = p_shl1_cast_mid2_v_fu_1002_p3;

assign p_shl1_cast_mid2_v_fu_1002_p3 = {{tmp_16_reg_2223}, {ap_const_lv3_0}};

assign p_shl1_cast_mid2_v_v_v_fu_796_p3 = ((exitcond_flatten_fu_756_p2[0:0] === 1'b1) ? n_V1_fu_770_p2 : t_V_1_phi_fu_472_p4);

assign p_shl2_cast_mid2_cast_fu_1130_p1 = p_shl2_cast_mid2_fu_1123_p3;

assign p_shl2_cast_mid2_fu_1123_p3 = ((exitcond_flatten_mid_reg_2241[0:0] === 1'b1) ? p_shl2_mid1_fu_1115_p3 : p_shl2_cast_mid_fu_1013_p3);

assign p_shl2_cast_mid_fu_1013_p3 = ((exitcond_flatten_reg_2203[0:0] === 1'b1) ? ap_const_lv7_0 : p_shl2_reg_2134);

assign p_shl2_fu_640_p3 = {{tmp_10_fu_636_p1}, {ap_const_lv2_0}};

assign p_shl2_mid1_fu_1115_p3 = {{tmp_18_fu_1112_p1}, {ap_const_lv2_0}};

assign p_shl3_cast_fu_1413_p1 = p_shl3_fu_1406_p3;

assign p_shl3_fu_1406_p3 = {{t_V_7_mid2_reg_2297}, {ap_const_lv2_0}};

assign p_shl4_fu_1370_p3 = {{tmp1_fu_1360_p2}, {ap_const_lv2_0}};

assign p_shl5_cast_fu_1972_p1 = p_shl5_fu_1964_p3;

assign p_shl5_fu_1964_p3 = {{tmp_29_fu_1960_p1}, {ap_const_lv3_0}};

assign p_shl6_cast_fu_2030_p1 = p_shl6_fu_2022_p3;

assign p_shl6_fu_2022_p3 = {{t_V_6_reg_557}, {ap_const_lv2_0}};

assign p_shl_cast_fu_666_p1 = p_shl_fu_658_p3;

assign p_shl_cast_mid1_fu_1144_p1 = p_shl_mid1_fu_1137_p3;

assign p_shl_cast_mid_fu_820_p1 = p_shl_mid_fu_812_p3;

assign p_shl_fu_658_p3 = {{tmp_6_fu_648_p2}, {ap_const_lv3_0}};

assign p_shl_mid1_fu_1137_p3 = {{tmp_6_mid1_reg_2273}, {ap_const_lv3_0}};

assign p_shl_mid_fu_812_p3 = {{tmp_13_fu_776_p1}, {ap_const_lv8_0}};

assign t_V_3_cast1_fu_632_p1 = t_V_3_phi_fu_494_p4;

assign t_V_3_cast1_mid1_fu_894_p1 = m_V_fu_874_p2;

assign t_V_3_mid2_fu_930_p3 = ((exitcond_flatten_mid_fu_868_p2[0:0] === 1'b1) ? m_V_fu_874_p2 : t_V_3_mid_fu_762_p3);

assign t_V_3_mid_fu_762_p3 = ((exitcond_flatten_fu_756_p2[0:0] === 1'b1) ? ap_const_lv6_0 : t_V_3_phi_fu_494_p4);

assign t_V_4_cast_fu_1980_p1 = t_V_4_reg_546;

assign t_V_5_cast1_fu_724_p1 = t_V_5_phi_fu_516_p4;

assign t_V_5_cast1_mid1_fu_1292_p1 = x_V_1_dup_fu_1287_p2;

assign t_V_5_cast2_mid2_cast_fu_1302_p1 = t_V_5_cast2_mid2_fu_1296_p3;

assign t_V_5_cast2_mid2_fu_1296_p3 = ((exitcond7_mid1_reg_2284[0:0] === 1'b1) ? x_V_1_dup_fu_1287_p2 : t_V_5_mid_reg_2266);

assign t_V_5_cast_fu_728_p1 = t_V_5_phi_fu_516_p4;

assign t_V_5_cast_mid1_fu_1306_p1 = x_V_1_dup_fu_1287_p2;

assign t_V_5_mid_fu_886_p3 = ((tmp_14_fu_880_p2[0:0] === 1'b1) ? ap_const_lv2_0 : t_V_5_phi_fu_516_p4);

assign t_V_6_cast_fu_2006_p1 = t_V_6_reg_557;

assign t_V_7_cast1_fu_1354_p1 = t_V_7_mid2_reg_2297;

assign t_V_7_cast_fu_958_p1 = t_V_7_mid2_fu_950_p3;

assign t_V_7_mid2_fu_950_p3 = ((tmp_19_fu_944_p2[0:0] === 1'b1) ? ap_const_lv2_0 : t_V_7_phi_fu_527_p4);

assign tmp10_fu_1378_p2 = (tmp1_cast_fu_1366_p1 + p_shl4_fu_1370_p3);

assign tmp17_fu_830_p2 = (t_V_5_cast1_fu_724_p1 + t_V_1_phi_fu_472_p4);

assign tmp1_0_1_fu_1461_p2 = (ap_const_lv10_5 + tmp10_reg_2390);

assign tmp1_0_2_fu_1476_p2 = (ap_const_lv10_A + tmp10_reg_2390);

assign tmp1_cast_fu_1366_p1 = tmp1_fu_1360_p2;

assign tmp1_fu_1360_p2 = (p_shl2_cast_mid2_cast_fu_1130_p1 + tmp3_cast_fu_1357_p1);

assign tmp3_cast_fu_1357_p1 = tmp3_reg_2303;

assign tmp3_fu_962_p2 = (t_V_7_cast_fu_958_p1 + t_V_3_mid2_fu_930_p3);

assign tmp4_cast_mid2177_v_fu_836_p3 = ((exitcond_flatten_fu_756_p2[0:0] === 1'b1) ? n_V1_fu_770_p2 : tmp17_fu_830_p2);

assign tmp4_cast_mid235_v_fu_904_p3 = ((exitcond_flatten_mid_fu_868_p2[0:0] === 1'b1) ? p_shl1_cast_mid2_v_v_v_fu_796_p3 : tmp4_cast_mid2177_v_fu_836_p3);

assign tmp4_cast_mid2_fu_1350_p1 = tmp4_cast_mid2_v_fu_1344_p3;

assign tmp4_cast_mid2_v_fu_1344_p3 = ((exitcond7_mid1_reg_2284[0:0] === 1'b1) ? tmp4_mid1_fu_1339_p2 : tmp4_cast_mid235_v_reg_2279);

assign tmp4_mid1_fu_1339_p2 = (t_V_5_cast1_mid1_fu_1292_p1 + p_shl1_cast_mid2_v_v_v_reg_2217);

assign tmp5_fu_1427_p2 = ($signed(p_6_cast_fu_1423_p1) + $signed(p_shl1_cast_mid2_fu_1009_p1));

assign tmp7_cast_fu_2002_p1 = tmp7_fu_1996_p2;

assign tmp7_fu_1996_p2 = (t_V_2_reg_534 + t_V_4_cast_fu_1980_p1);

assign tmp8_fu_2044_p2 = ($signed(p_shl5_cast_reg_2707) + $signed(p_4_cast_fu_2040_p1));

assign tmp_10_fu_636_p1 = t_V_3_phi_fu_494_p4[4:0];

assign tmp_11_fu_598_p1 = t_V_reg_446[1:0];

assign tmp_13_fu_776_p1 = n_V1_fu_770_p2[5:0];

assign tmp_14_fu_880_p2 = (exitcond_flatten_mid_fu_868_p2 | exitcond_flatten_fu_756_p2);

assign tmp_15_1_cast_mid2_cast_fu_1322_p1 = tmp_15_1_cast_mid2_fu_1315_p3;

assign tmp_15_1_cast_mid2_fu_1315_p3 = ((exitcond7_mid1_reg_2284[0:0] === 1'b1) ? x_V_1_mid1_fu_1310_p2 : tmp_15_1_cast_mid_fu_1275_p3);

assign tmp_15_1_cast_mid_fu_1275_p3 = ((tmp_14_reg_2260[0:0] === 1'b1) ? ap_const_lv2_1 : x_V_1_reg_2184);

assign tmp_15_2_cast_mid2_cast_fu_1507_p1 = tmp_15_2_cast_mid2_reg_2385;

assign tmp_15_2_cast_mid2_fu_1332_p3 = ((exitcond7_mid1_reg_2284[0:0] === 1'b1) ? tmp_15_2_mid1_fu_1326_p2 : tmp_15_2_cast_mid_fu_1281_p3);

assign tmp_15_2_cast_mid_fu_1281_p3 = ((tmp_14_reg_2260[0:0] === 1'b1) ? ap_const_lv3_2 : tmp_15_2_reg_2189);

assign tmp_15_2_fu_738_p2 = (ap_const_lv3_2 + t_V_5_cast_fu_728_p1);

assign tmp_15_2_mid1_fu_1326_p2 = (ap_const_lv3_2 + t_V_5_cast_mid1_fu_1306_p1);

assign tmp_15_fu_1858_p1 = $signed(ap_reg_ppstg_tmp_12_reg_2412_pp0_iter2);

assign tmp_16_fu_804_p1 = p_shl1_cast_mid2_v_v_v_fu_796_p3[5:0];

assign tmp_17_0_1_fu_1471_p1 = i_index_V_0_1_fu_1466_p2;

assign tmp_17_0_2_fu_1486_p1 = i_index_V_0_2_fu_1481_p2;

assign tmp_17_1_1_fu_1534_p1 = i_index_V_1_1_fu_1530_p2;

assign tmp_17_1_2_fu_1543_p1 = i_index_V_1_2_fu_1539_p2;

assign tmp_17_1_fu_1401_p1 = i_index_V_1_fu_1395_p2;

assign tmp_17_2_1_fu_1603_p1 = i_index_V_2_1_reg_2494;

assign tmp_17_2_2_fu_1639_p1 = i_index_V_2_2_reg_2499;

assign tmp_17_2_fu_1599_p1 = i_index_V_2_reg_2489;

assign tmp_17_fu_938_p2 = (exitcond7_mid1_fu_924_p2 | exitcond_flatten_mid_fu_868_p2);

assign tmp_18_fu_1112_p1 = m_V_reg_2255[4:0];

assign tmp_19_fu_944_p2 = (tmp_17_fu_938_p2 | exitcond_flatten_fu_756_p2);

assign tmp_1_fu_620_p1 = t_V_1_phi_fu_472_p4[5:0];

assign tmp_20_0_1_fu_1702_p1 = $signed(tmp_20_fu_1695_p3);

assign tmp_20_0_2_fu_1725_p3 = {{tmp_21_fu_1715_p4}, {ap_const_lv30_0}};

assign tmp_20_1_1_fu_1778_p3 = {{tmp_23_fu_1768_p4}, {ap_const_lv30_0}};

assign tmp_20_1_2_fu_1805_p3 = {{tmp_24_reg_2639}, {ap_const_lv30_0}};

assign tmp_20_1_fu_1752_p3 = {{tmp_22_reg_2624}, {ap_const_lv30_0}};

assign tmp_20_2_1_fu_1869_p3 = {{tmp_26_reg_2654}, {ap_const_lv30_0}};

assign tmp_20_2_2_fu_1895_p3 = {{tmp_27_fu_1885_p4}, {ap_const_lv30_0}};

assign tmp_20_2_fu_1831_p3 = {{tmp_25_fu_1821_p4}, {ap_const_lv30_0}};

assign tmp_20_fu_1695_p3 = {{tmp_s_reg_2604}, {ap_const_lv30_0}};

assign tmp_2115_0_1_cast_fu_1706_p1 = $signed(p_Val2_7_0_1_reg_2614);

assign tmp_2115_0_2_cast_fu_1733_p1 = $signed(p_Val2_7_0_2_reg_2619);

assign tmp_2115_1_1_cast_fu_1786_p1 = $signed(p_Val2_7_1_1_reg_2629);

assign tmp_2115_1_2_cast_fu_1812_p1 = $signed(p_Val2_7_1_2_reg_2634);

assign tmp_2115_1_cast_fu_1759_p1 = $signed(p_Val2_7_1_reg_2609);

assign tmp_2115_2_1_cast_fu_1876_p1 = $signed(p_Val2_7_2_1_reg_2649);

assign tmp_2115_2_2_cast_fu_1903_p1 = $signed(p_Val2_7_2_2_reg_2659);

assign tmp_2115_2_cast_fu_1839_p1 = $signed(p_Val2_7_2_reg_2644);

assign tmp_21_fu_1715_p4 = {{p_Val2_8_0_1_fu_1709_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_23_fu_1768_p4 = {{p_Val2_8_1_fu_1762_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_25_fu_1821_p4 = {{p_Val2_8_1_2_fu_1815_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_27_fu_1885_p4 = {{p_Val2_8_2_1_fu_1879_p2[ap_const_lv32_3D : ap_const_lv32_1E]}};

assign tmp_28_fu_1439_p1 = o_index_V_fu_1433_p2[1:0];

assign tmp_29_fu_1960_p1 = t_V_2_reg_534[5:0];

assign tmp_30_fu_2054_p1 = index_V_fu_2049_p2[1:0];

assign tmp_31_fu_2098_p1 = biased_V_fu_2093_p2[30:0];

assign tmp_3_fu_2058_p4 = {{index_V_fu_2049_p2[ap_const_lv32_A : ap_const_lv32_2]}};

assign tmp_4_fu_1955_p1 = t_V_2_reg_534;

assign tmp_5_fu_2068_p1 = $signed(tmp_3_fu_2058_p4);

assign tmp_6_cast1_fu_654_p1 = tmp_6_fu_648_p2;

assign tmp_6_cast1_mid1_fu_1134_p1 = tmp_6_mid1_reg_2273;

assign tmp_6_cast1_mid_fu_808_p1 = p_mid1_fu_780_p3;

assign tmp_6_fu_648_p2 = (p_s_fu_624_p3 + t_V_3_cast1_fu_632_p1);

assign tmp_6_mid1_fu_898_p2 = (p_mid2_fu_788_p3 + t_V_3_cast1_mid1_fu_894_p1);

assign tmp_7_fu_670_p2 = (p_shl_cast_fu_666_p1 + tmp_6_cast1_fu_654_p1);

assign tmp_7_mid1_fu_1148_p2 = (p_shl_cast_mid1_fu_1144_p1 + tmp_6_cast1_mid1_fu_1134_p1);

assign tmp_7_mid_fu_824_p2 = (p_shl_cast_mid_fu_820_p1 + tmp_6_cast1_mid_fu_808_p1);

assign tmp_8_fu_2102_p2 = (($signed(biased_V_reg_2763) > $signed(32'b00000000000000000000000000000000)) ? 1'b1 : 1'b0);

assign tmp_9_fu_1390_p1 = i_index_V_fu_1384_p2;

assign w_index_V_0_1_fu_676_p2 = (ap_const_lv15_3 + tmp_7_fu_670_p2);

assign w_index_V_0_1_mid1_fu_1166_p2 = (ap_const_lv15_3 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_0_1_mid_fu_1024_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_3);

assign w_index_V_0_2_fu_682_p2 = (ap_const_lv15_6 + tmp_7_fu_670_p2);

assign w_index_V_0_2_mid1_fu_1184_p2 = (ap_const_lv15_6 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_0_2_mid_fu_1035_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_6);

assign w_index_V_1_1_fu_694_p2 = (ap_const_lv15_4 + tmp_7_fu_670_p2);

assign w_index_V_1_1_mid1_fu_1210_p2 = (ap_const_lv15_4 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_1_1_mid_fu_1057_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_4);

assign w_index_V_1_2_fu_700_p2 = (ap_const_lv15_7 + tmp_7_fu_670_p2);

assign w_index_V_1_2_mid1_fu_1223_p2 = (ap_const_lv15_7 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_1_2_mid_fu_1068_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_7);

assign w_index_V_1_fu_688_p2 = (ap_const_lv15_1 + tmp_7_fu_670_p2);

assign w_index_V_1_mid1_fu_1197_p2 = (ap_const_lv15_1 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_1_mid_fu_1046_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_1);

assign w_index_V_2_1_fu_712_p2 = (ap_const_lv15_5 + tmp_7_fu_670_p2);

assign w_index_V_2_1_mid1_fu_1249_p2 = (ap_const_lv15_5 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_2_1_mid_fu_1090_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_5);

assign w_index_V_2_2_fu_718_p2 = (ap_const_lv15_8 + tmp_7_fu_670_p2);

assign w_index_V_2_2_mid1_fu_1262_p2 = (ap_const_lv15_8 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_2_2_mid_fu_1101_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_8);

assign w_index_V_2_fu_706_p2 = (ap_const_lv15_2 + tmp_7_fu_670_p2);

assign w_index_V_2_mid1_fu_1236_p2 = (ap_const_lv15_2 + tmp_7_mid1_fu_1148_p2);

assign w_index_V_2_mid_fu_1079_p2 = (tmp_7_mid_reg_2228 | ap_const_lv15_2);

assign x_V_1_dup_fu_1287_p2 = (ap_const_lv2_1 + t_V_5_mid_reg_2266);

assign x_V_1_fu_732_p2 = (ap_const_lv2_1 + t_V_5_phi_fu_516_p4);

assign x_V_1_mid1_fu_1310_p2 = (t_V_5_mid_reg_2266 ^ ap_const_lv2_2);

assign x_V_fu_1990_p2 = (t_V_4_reg_546 + ap_const_lv2_1);

assign y_V_1_fu_968_p2 = (t_V_7_mid2_fu_950_p3 + ap_const_lv2_1);

assign y_V_fu_2016_p2 = (t_V_6_reg_557 + ap_const_lv2_1);

always @ (posedge ap_clk) begin
    p_shl2_reg_2134[1:0] <= 2'b00;
    tmp_7_mid_reg_2228[4:0] <= 5'b00000;
    t_V_5_cast2_mid2_cast_reg_2373[9:2] <= 8'b00000000;
    tmp_15_1_cast_mid2_cast_reg_2379[9:2] <= 8'b00000000;
    p_shl5_cast_reg_2707[2:0] <= 3'b000;
    p_shl5_cast_reg_2707[10:9] <= 2'b00;
    p_Val2_1_cast_reg_2712[31:27] <= 5'b00000;
    tmp7_cast_reg_2725[10:7] <= 4'b0000;
end

endmodule //dut_perform_conv_1
